### ISSUE TITLE
Conditional Access "Require app protection policy" flow with ADAL

### ISSUE THREAD

**Issue by Ddv0623** [microsoftconnect/ms-intune-app-sdk-ios#209]
ADAL: 6
Intune SDK:14.7.1

I am working on React Native app using ADAL. I want to know how to correctly implement CA flow. As I read document in code will call to get token as normal then it will get error and we can handle by call
 [[IntuneMAMComplianceManager instance] remediateComplianceForIdentity]
after that ADAL should get token, right?

As I try first time call ADAL 
but can not get correct error as in document.
A web page show issue then force to close 
![IMG_0017](https://user-images.githubusercontent.com/26756794/138508021-b3f3bb5e-656f-4ce6-b636-ef026891f013.jpeg)

I see part set "required: claims = {"access_token":{"xms_cc":{"values":["protapp"]}}}"
but in document example is using MSAL so I don't know how to do it for ADAL

I have set 
ADALAuthority
ADALRedirectUri
ADALClientId
under IntuneMAMSettings in info.plist

I am new with iOS native code since I work on React Native project. Hope you guys can help me.

**Additional context:**
- when I try call remediate first then get ADAL token, it still not work.
- when I try loginAndEnrollAccount it popup dialog like below
![IMG_0018](https://user-images.githubusercontent.com/26756794/138507945-bef6f613-7c8e-458d-adf2-966be712caae.png)
(I know that I should not use this method, but I just want to try it out to see if it work

**Comment by gastaffo** [comment]
@ankitpoplify . @Ddv0623 Are y'all still facing these issues?

**Comment by gastaffo** [comment]
@ankitpoplify @Ddv0623 As a heads up I will be closing this issue in 2 weeks due to inactivity.

**Comment by Ddv0623** [comment]
> @ankitpoplify . @Ddv0623 Are y'all still facing these issues?
Sorry @gastaffo for late reply, I will work on this issue this week and let you know the result.

**Comment by ankitpoplify** [comment]
@gastaffo The token will not expire unless I call msal sign out api, right? Intunes keeps checking for policy from time to time, right? Do, I need to do changes in my code for this scenario?

**Comment by ankitpoplify** [comment]
@gastaffo Okay great. One more thing in this scenario do I receive `interactionRequired` error in `IntuneComplianceDelegate`?

**Comment by ankitpoplify** [comment]
@gastaffo So, according to you if I apply CA on an already logged-in user then CA will work for the user only next time when I try to acquire a new token for that user?

**Comment by gastaffo** [comment]
@ankitpoplify The SDK should also Prompt the user to login by itself not just when you acquire the token

**Comment by ankitpoplify** [comment]
@gastaffo Which method in the sdk triggers the Prompt to user to login?

**Comment by gastaffo** [comment]
@ankitpoplify The SDK will do it automatically the app doesn't need to interact with the SDK directly for it to work.

**Comment by ankitpoplify** [comment]
@gastaffo Thank you so much for the help. I really appreciate it.

**Comment by gastaffo** [comment]
@ankitpoplify No problem, happy to help!

**Comment by Ddv0623** [comment]
@gastaffo When I switch to using MSAL, do the same as your example. Now I able to get accessToken with CA on.
Thanks you

**Comment by Ddv0623** [comment]
I think MS should mention the warp example in document https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-ios
in document right now just have "chart" project as example and it using swift.
with warp project it have detail about how make app work with Conditional Access get token by MSAL and using Objective C which help a lot since I using React Native which is using Objective C.

**Comment by gastaffo** [comment]
@Ddv0623 Glad to hear its working. Thanks for the suggestion, we will look into providing more Obj-C examples of CA and MSAL.

**Comment by parveen-bhatia** [comment]
@gastaffo or @ankitpoplify when App CA is applied after user is enrolled with Intune. Then from the conversation it seems App CA policy would be applied, when next time SDK will try to acquire a token. And during that, SDK will automatically prompt the user to re-authenticate with Azure AD. From some testing, it seems refresh tokens can take couple of months to expire unless [App CA is configured](https://learn.microsoft.com/en-us/azure/active-directory/conditional-access/howto-conditional-access-session-lifetime#user-sign-in-frequency).
Does it mean App CA policy would not be effective until then ?
