### ISSUE TITLE
Enrollment failed with status code 201 and returning legacy result code 6

### ISSUE THREAD

**Issue by nevertheless1975** [microsoftconnect/ms-intune-app-sdk-ios#316]
**Describe the bug:**

Some managed devices fail to enroll showing error with code 201 and result code 6. 

**To Reproduce**

For those devices the error will occur with every app startup triggering the enrollment process. 

**Expected behavior:**

The enrollment should not always fail with error 201. 

**Screenshots and logs:**

I can provide more logs via direct message. Here are the three lines showing the error. 

> 2023-03-21T08:59:45.429Z ERRO <BUNDLE_ID> 0
> IntuneMAM: CMAROperationScheduler: Enrollment failed with status code 201 and error code 0
> …
> 2023-03-21T08:59:45.429Z INFO <BUNDLE_ID> 0
> IntuneMAM: MAM_CHECKPOINT: CMARMamServiceManager: Received enrollment result of 201 and returning legacy result code of 6
> …
> 2023-03-21T08:59:45.448Z ERRO <BUNDLE_ID> 0
> IntuneMAM: Auto-enrollment failed. Result code from MAM Service Manager: 6

**Smartphone (please complete the following information):**
 - Device: iPhone XE 2
 - OS: latest

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version?

16.1.1 

- What platform is your app based in (native, Xamarin based, Cordova, etc)?

Cordova

- Do you see a trend with it only being reproduced on a specific device?

Yes. There are a few devices where it always happens. All are managed. 

**Additional context:**

The application login is not MSAL based. Therefore loginAndEnroll API is used. After the login is completed, the enrollment fails with error 201 / result code 6. For most of the phones it works just fine. 

What is the legacy code 6 meaning? 

Is there a way to get more details from within the Intune portal about a possible root cause?

**Comment by nevertheless1975** [comment]
Hi. 

has anyone an opinion on above? I mean at least what the error codes stand for and in which situations they would occur?

Regards,

Andreas

**Comment by nevertheless1975** [comment]
Hi,

unfortunately this keeps happening even on non-managed devices and without above application config in place. 

Can anyone from Intune team tell me what exactly the error code 201 in combination with legacy code 6 means?

Regards,

Andreas

**Comment by nevertheless1975** [comment]
@chadseippel do you have any thoughts on this?

**Comment by ShruthiAchutha** [comment]
Closing stale issues. Please reopen if you still need help with this.
