### ISSUE TITLE
Linking of InTuneMAMSwift frameworks causes CarPlay initiated Siri requests to stall.

### ISSUE THREAD

**Issue by StuSharpe** [microsoftconnect/ms-intune-app-sdk-ios#322]
**Describe the bug:**
Linking of these Intune SDK frameworks:
  - `IntuneMAMSwift.xcframework`
  - `IntuneMAMSwiftStub.xcframework`

causes Siri Intent Responses initiated via CarPlay (using the `INStartCallIntent`) to be stalled until the user brings the CarPlay scene into the foreground.

In particular, the [UISceneDelegate.scene(_:continue:)](https://developer.apple.com/documentation/uikit/uiscenedelegate/3238056-scene) method in the CarPlay `UISceneDelegate` does not get called immediately as expected. But rather this action is 'queued up' and will not trigger until either:
* the app is foregrounded by touching the app icon in CarPlay.
* or, the scene is backgrounded/foregrounded on the phone.

Simply unlinking the above frameworks resolves this issue, and Siri requests are relayed immediatey to the app via the [UISceneDelegate.scene(_:continue:)](https://developer.apple.com/documentation/uikit/uiscenedelegate/3238056-scene) method.

**To Reproduce**

Full Xcode demo project is available on request, but the setup is this:

1. iOS project, that is set up for CarPlay with 'supports multiple scenes' enabled in the `Info.plist`, and seperate `UISceneDelgate` implementations for CarPlay (Info.plist attached)
2. These InTune SDK frameworks included:
  - `IntuneMAMSwift.xcframework`
  - `IntuneMAMSwiftStub.xcframework`
3. No other integration of InTune SDK features at runtime, (no `import IntuneMAMSwift` statements) just linking the libs is enough to reproduce the issue.
4. Project has a single Siri Intents Extension, that implements the `INStartCallIntent` Intent
5. The Siri Extension will pass the contact onto the app using the [.continueInApp](https://developer.apple.com/documentation/sirikit/instartcallintentresponsecode/continueinapp) response code.

Reproduction Steps:
1. Launch the app on the phone
2. Connect phone to CarPlay 
3. Say a Siri Phrase *using the CarPlay Siri function* that activates the `INStartCallIntent` (e.g. "Call (NAME) using (APP)")
4. Siri confirms the phrase "Call (NAME) using (APP)..."
5. Wait for a while (minutes).  Nothing happens (unexpected)
6. Tap the app icon in CarPlay 
7. The Siri action will finally trigger at this point 

**Expected behavior:**

1. Launch the app on the phone
2. Connect to CarPlay 
3. Say a Siri Phrase *using the CarPlay Siri function* that activates the `INStartCallIntent` (e.g. "Call <NAME> using <APP>")
4. Siri confirms the phrase "Calling <NAME> using <APP>..."
5. The Siri action triggers in app with no user interaction required

As noted above, simply unlinking the Intune SDK frameworks (removing completely from the project) is enough to restore the expected behavior

**Screenshots and logs:**
[Info.plist](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/files/11107309/Info_plist.txt)

**Smartphone :**
 - Device: iPhone 11 Pro
 - OS: iOS 16.1.2
 - CarPlay Simulator (on macOS 12.6.3)

Also confirmed on iOS 15.5, and using real CarPlay hardware.

**Intune App SDK for iOS :**

- iOS native codebase (Swift/Obj-c)
- Xcode 14.2 

- msintuneappsdk/ms-intune-app-sdk-ios 17.3.2
- AzureAD/azure-activedirectory-library-for-objc 6.0.4

**Additional context:**

As mentioned above, a demo project is available if it helps.  (would require developer CarPlay entitlement on the Apple Developer account to run through CarPlay)

This seems specfic to Siri requests initiated via CarPlay.  Siri requests initiated via the phone don't seem to exhibit this problem.

But any suggestions in the meantime are appreciated.

**Comment by StuSharpe** [comment]
Here's a [video demonstrating the problem](https://drive.google.com/file/d/1ErSR4iNNyE0PI54JpKbYlgk605gePWh7/view?usp=share_link) described above. 

Any suggestions would be greatly appreciated.

**Comment by darosal** [comment]
Hi @StuSharpe, thanks for reaching out and thanks for the repro video of what's happening. 

Just as a few sanity tests, does the behavior persist after following all the setup steps listed in the [Build the SDK into your mobile app](https://learn.microsoft.com/mem/intune/developer/app-sdk-ios#build-the-sdk-into-your-mobile-app) section of our docs?

Also, you had mentioned "Siri requests initiated via the phone don't seem to exhibit this problem", is this true when the request is initiated while the device is locked? I noticed on a local repro that the Siri intent will launch the app using CallKit if the device is unlocked (foregrounding it) but will not do so if the device is locked.

**Comment by StuSharpe** [comment]
Hi @darosal 

So, it seems the static lib workaround (above) has turned out to be a red-herring.  Once I got [the static lib linking correctly,](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/issues/326) the problem reappeared.

So I think we're back to square one here.  Having working Siri integration is a requirement to ship a CarPlay-enabled app on the app store, so this is a big blocker for us right now.  So more than happy to try out any suggestions you may have.

Stu.

**Comment by ShruthiAchutha** [comment]
Closing stale issues. Please reopen if you still need help with this.
