### ISSUE TITLE
App crashing on loginAndEnrollAccount cal

### ISSUE THREAD

**Issue by mahavrani** [microsoftconnect/ms-intune-app-sdk-ios#425]
Describe the bug:
The app is crashing on loginAndEnrollAccount.Used Option 2 (Static library approach)

<img width="1123" alt="Screenshot 2024-04-27 at 8 29 58 PM" src="https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/assets/18703776/cbf945c3-d617-4ee4-8388-8aa6c4ce1aed">
<img width="1116" alt="Screenshot 2024-04-27 at 8 29 51 PM" src="https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/assets/18703776/a0f7ec40-52d2-43b8-a9bd-778a003c3bc5">
<img width="1381" alt="Screenshot 2024-04-29 at 5 11 05 PM" src="https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/assets/18703776/1a65dbff-3eba-4aa9-9a54-f0cb4c3e7086">
 with sample app provided with Intune 

To Reproduce
Run the sample app provided bu Intune with Static library approach Option 2 integration in loginAndEnrollAccount then the app crashes.

Expected behavior:
App should not crash even the framework referred from another framework.

Screenshots and logs:
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle: 'NSBundle </Users/<>Library/Developer/CoreSimulator/Devices/C12954FF-809E-4931-9F46-D28AE1166868/data/Containers/Bundle/Application/50940FE0-4C6C-434E-9678-CBF88738CA2F/InforGoCoreApp.app> (loaded)' with name 'PolicyViewController_iPhone''

Smartphone (please complete the following information):

Device: [e.g. iPhone6] -iPhone XR
OS: [e.g. iOS8.1] -iOS 16.5
Intune App SDK for iOS (please complete the following information):

What version of the Intune SDK are you using? Are you using the latest version? -19.3.1

What platform is your app based in (native, Xamarin based, Cordova, etc)? -native.Using chat sample app provided by Intune only.

For errors during build, does the app build without Intune SDK integration? -No

For errors post build, does the app launch without being Intune SDK integrated? -Yes

Do you see a trend with it only being reproduced on a specific device? -No

Additional context:

**Comment by mahavrani** [comment]
Please let us know if there is any update on above issue faced during Option 2 approach

**Comment by ChismanRaheem** [comment]
Hi please download and test our newest version which we added new static framework SDK variant: IntuneMAMStatic.xcframework. This variant will replace the existing static library variant (libIntuneMAMSwift.xcframework). For more information please see our https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/discussions/432

**Comment by ChismanRaheem** [comment]
HI @mahavrani There has been no actions for over 90 days, and I will be archiving case. If you are still experiencing any issues, please reach out so that we can continue efforts.
