### ISSUE TITLE
App crashes on malloc request after app restart triggered by Intune SDK

### ISSUE THREAD

**Issue by niminim44** [microsoftconnect/ms-intune-app-sdk-ios#426]
Describe the bug:
C++ call to malloc crashes the app after a restart has been triggered by Intune SDK. 

To Reproduce
1. Launch the app and trigger a successful loginAndEnroll request.
2. wait for APP to be calculated and for Intune to trigger an app restart.
3. App will crash on my low level SDK when it calls malloc.

Expected behavior:
Expecting app not to crash, malloc requests should work, and Intune should apply APP correctly.

tested on different devices and different OS versions. crash is consistent.

Intune App SDK for iOS (please complete the following information):
- What version of the Intune SDK are you using? Are you using the latest version? **using latest version 9.2.0**
- What platform is your app based in (native, Xamarin based, Cordova, etc)? **App is native.**
- For errors during build, does the app build without Intune SDK integration? ---
- For errors post build, does the app launch without being Intune SDK integrated? **YES**

- Who is the customer? **Any intune user that has APP**
- Do you see a trend with it only being reproduced on a specific device? **NO**

**Comment by jitheshncxe** [comment]
@niminim44 , had you collected/reviewed crash logs and see if that can provide additional clues? if so, do you see any of the MAM SDK APis on the stack? REF: https://developer.apple.com/library/archive/technotes/tn2151/_index.html

**Comment by niminim44** [comment]
Hi @jitheshncxe 

The crash logs have no MAM SDK APIs, but I have a feeling this is related to one of Intune hooks on app launch.

I am using Chromium in my code, and it has some checks related to the validity of memory zones in the app:
https://chromium.googlesource.com/external/github.com/google/proto-quic/+/refs/heads/merge-to-59.0.3056.0/src/base/allocator/malloc_zone_functions_mac.cc#26

This macro function is evaluated to be false since all the function pointers are NULL. As a result the app crashes.

**Comment by jitheshncxe** [comment]
@niminim44, could you please share the full crash logs for me to take a look?

**Comment by niminim44** [comment]
![image (1)](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/assets/38298170/ad60efbf-84b2-48e2-a338-34038dd38e13)

**Comment by jitheshncxe** [comment]
Thanks @niminim44...Given the crash logs don't give us a clue, is it possible for you to share a minimal project which we could use to reproduce the error locally?

**Comment by niminim44** [comment]
From privacy concerns I would prefer not to share it on this thread. Can you please send me (niminim44@gmail.com) or share here an email that I can share it with? (or any other private communication )
THX!

**Comment by jitheshncxe** [comment]
@niminim44 , just checking if you had received an email from my official id and could share the repro and full crash logs so that we can look further into this issue...Thanks!

**Comment by niminim44** [comment]
all good found the issue, thx for the help =]
