### ISSUE TITLE
Help with MAM enrollment error code 225

### ISSUE THREAD

**Issue by YoonLee** [microsoftconnect/ms-intune-app-sdk-ios#434]
**Objectives**: Enrollment MAM Policies & MSAL authenticate
**Devices type**: MDM iPad devices
**App use**: Non-public, distribute only through Intunes to MDM devices
**Authenticator app**: We do not pre-install authenticator app for MDM devices
**Audience**: Registered azure users in organization group

**Current app settings**:
- `IntuneMAMSettings` dictionary included in `info.plist`
- `AutoEnrollOnLaunch=YES` and `MAMPolicyRequired=YES`

**Entra app permission API settings**:
- MS Graph Delegated - [email, offline_access, openid, profile, User.Read, User.Read.All]
- Microsoft Mobile Application Management (1) - DeviceManagementManagedApps.ReadWrite

**Behaviors**:
1. App launches
2. SSO page displays on the App with the title - Accessing your organization's data.
3. SSO with organization credential
4. Splash page displays with Checking your organization's data access requirements for this app.
5. IntuneMAMEnrollmentDelegate receives the **error code 225- The account is licensed for Intune but is not targeted with MAM policy.**

**Querstions**:

Q1) Are the app bundle id `com.acme.nameOfApp` should only include lower cases? Otherwise, it won't able to read bundle id?
Q2) Can you give me any recommendation permission API should include to support?
Q3) Which area should we work on to avoid 225 issue on Entra page? S.A. Manifest `json` file or Manage - Users and group?
Q4) I read other similar thread here saying about 225"tenant administrator has not targeted any policies to this app for this user." I want to know what exactly this mean and make a change.

**Comment by wangxiaoms** [comment]
Hi you can follow below procedure
https://learn.microsoft.com/en-us/mem/intune/apps/app-protection-policies#create-an-iosipados-or-android-app-protection-policy
The Apps page allows you to choose which apps should be targeted by this policy. You must add at least one app. I assume your bundle ID is case-insensitive, please use lower case. 
The Assignments page allows you to assign the app protection policy to groups of users. You must apply the policy to a group of users to have the policy take effect.

**Comment by pschugt** [comment]
Hi @YoonLee 

> 5. IntuneMAMEnrollmentDelegate receives the **error code 225- The account is licensed for Intune but is not targeted with MAM policy.**

For me this sounds like no app configuration settings are applied or setup?
App configuration settings are required with atleast IntuneMAMUPN configured.

Can you check that in your tennant please.

**Comment by wangxiaoms** [comment]
closing, question answered.
