### ISSUE TITLE
We are receiving 225 error, but user has MAM policies

### ISSUE THREAD

**Issue by byhkalo** [microsoftconnect/ms-intune-app-sdk-ios#440]
**Describe the bug:**
Right now, after the user's authentication, we are trying to apply a MAM policies (enrolled the user).
Our customer guarantee, that all their users has MAM policies. But we still receive 225 error on our side.

Status Code: 225
Error String: Optional("The account is licensed for Intune but is not targeted with MAM policy.")

Sometimes, after 30 minutes policies finally applied, but not on the authentication step.

**Expected behavior:**
MAM policies applied immediately

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version?
 -> 19.3.1

- What platform is your app based in (native, Xamarin based, Cordova, etc)?
-> Native iOS

**Comment by pmod2** [comment]
Closing the issue in absence of logs.
