### ISSUE TITLE
Application stuck on `Checking your organization's data access requirements for this app`

### ISSUE THREAD

**Issue by byhkalo** [microsoftconnect/ms-intune-app-sdk-ios#441]
**Describe the bug:**
When a user is trying to log in to the account, after the selection of the account in Authenticator application and returned back - user stuck on the page `Checking your organization's data access requirements for this app` for a while and this page is not dismissed finally. 

**Pre Conditions**
- User has MDM enrolled device (under Company portal)
- User has Authenticator app with logged in account
- User has MAM Policies
- User doesn't have Conditional Access

**Steps to reproduce the behavior:**
1. User login first time to the application - everything is fine
2. User logs out from the application (without application restart)
3. User is truing to login second time
4. User selected account in Authenticator
5. User redirected back to the app and stuck on this screen

**Workaround:**
User can kill the application and open it again - problem solved

**Expected behavior:**
User redirected back to the app and policies applied successfully

**Screenshots and logs:**
![OIDC_login_checking_page_stuck](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/assets/12058642/a03d063c-6f35-46a9-80b1-9826964d49d9)

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version?
-> 19.3.1
- What platform is your app based in (native, Xamarin based, Cordova, etc)?
-> Native iOS

**Comment by pmod2** [comment]
Kindly contact me directly at priyankamodi@microsoft.com to provide additional details that might include PII, which may not be suitable for public disclosure:
User ID:
Intune Device ID:
Applications info (app id, app version, type, MSAL version if applicable)-
OS version:
Intune Logs ID:
MAM logs for LOB/1P app:

**Comment by pmod2** [comment]
@byhkalo - Requesting above logs if the issue repro is still happening.

**Comment by pmod2** [comment]
Marking this as complete as no response received.
[x] #441

**Comment by byhkalo** [comment]
Will try to reproduce the issue again today and I'll share additional details soon
