### ISSUE TITLE
[Question] How to use token obtained from AWS Amplify for Intune MAM configuration instead of switching to MSAL?

### ISSUE THREAD

**Issue by lhhiep2204** [microsoftconnect/ms-intune-app-sdk-ios#443]
Hi,

I'm currently using AWS Amplify to log in to Azure AD in my iOS application. This approach gives me an authentication token that I use for my app's authentication flow. However, now I need to integrate Microsoft Intune Mobile Application Management (MAM) into my app.

I understand that Intune SDK typically integrates with MSAL (Microsoft Authentication Library) to handle authentication. My question is:
- Is there a way to use the token obtained from AWS Amplify to configure Intune MAM in my application?
- If not, is switching to MSAL the only way to properly integrate Intune MAM?

**Comment by wangxiaoms** [comment]
Yes, you are required to integrate with MSAL before integrating the Intune SDK. 
https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-ios-phase1#should-my-application-integrate-the-microsoft-authentication-library-msal

**Comment by lhhiep2204** [comment]
> Yes, you are required to integrate with MSAL before integrating the Intune SDK. https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-ios-phase1#should-my-application-integrate-the-microsoft-authentication-library-msal

The link below discusses configuration when the app doesn't use MSAL. Could you explain it to me more clearly?
Thank you!
https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-ios-phase3#apps-that-dont-use-adal-or-msal

**Comment by wangxiaoms** [comment]
> The link below discusses configuration when the app doesn't use MSAL. Could you explain it to me more clearly? Thank you! https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-ios-phase3#apps-that-dont-use-adal-or-msal

With this API (loginAndEnrollAccount) the Intune SDK handles login and enrollment. MSAL SDK still needs to be integrated for the authentication function.

**Comment by lhhiep2204** [comment]
> > The link below discusses configuration when the app doesn't use MSAL. Could you explain it to me more clearly? Thank you! https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-ios-phase3#apps-that-dont-use-adal-or-msal
> 
> With this API (loginAndEnrollAccount) the Intune SDK handles login and enrollment. MSAL SDK still needs to be integrated for the authentication function.

So if my app doesn't have a login feature, I can still apply Intune policy without integrating MSAL for the authentication function, right?

**Comment by wangxiaoms** [comment]
> So if my app doesn't have a login feature, I can still apply Intune policy without integrating MSAL for the authentication function, right?

Yes the SDK will prompt the user for credentials, then try to enroll the app with the Intune MAM service on behalf of the supplied user account.
