### ISSUE TITLE
The operation failed because the Intune MAM SDK failed received a nil value for the user\'s account UPN.

### ISSUE THREAD

**Issue by redPanda0147** [microsoftconnect/ms-intune-app-sdk-ios#444]
I am getting error while adding upn to intune sdk.

`IntuneMAMEnrollmentManager.instance().registerAndEnrollAccount(upn)`

`print(status.statusCode.rawValue)`
207

`print(status.didSucceed)`
false

`print(status.errorString)`
The operation failed because the Intune MAM SDK failed received a nil value for the user\'s account UPN.

`print((status.error as? NSError)?.localizedDescription)`
Invalid identity. Could not find AAD object id for account: xxxxxxx@xxxxxxx.onmicrosoft.com

`print("userInfo: ", (status.error as? NSError)?.userInfo)`
["NSLocalizedDescription": Invalid identity. Could not find AAD object id for account: xxxxxxx@xxxxxxx.onmicrosoft.com]

**MOST IMPORTANT**
One user is able to enroll but all the other user is not able to enroll themself.

**Comment by wangxiaoms** [comment]
Hi it is recommended to use registerAndEnrollAccountId method and accountId parameter:
(void)registerAndEnrollAccountId:(NSString *_Nonnull)accountId;
https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-ios-phase3#apps-that-already-use-adal-or-msal

Can you try above with latest SDK version, If it still fails, can you get MAM logs:
https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-ios-appendix#how-can-i-troubleshoot-my-app

**Comment by redPanda0147** [comment]
Hello @wangxiaoms 

Thanks for your response. If I pass id into method, i am getting this error:

["NSUnderlyingError": Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALErrorDescriptionKey=AADSTS65001: The user or administrator has not consented to use the application with ID 'app-id-here' named 'app-name-here'. Send an interactive authorization request for this user and resource. Trace ID: 31a36ccb-b756-41d6-bd4a-f92938461d00 Correlation ID: 19391f44-4986-49fd-82b8-066b9abe44c9 Timestamp: 2024-06-20 13:27:19Z, MSALOAuthErrorKey=invalid_grant, MSALOAuthSubErrorKey=consent_required, MSALCorrelationIDKey=19391F44-4986-49FD-82B8-066B9ABE44C9, MSALInternalErrorCodeKey=-42004}, "MSALOAuthSubErrorKey": consent_required, "MSALOAuthErrorKey": invalid_grant, "MSALCorrelationIDKey": 81234664-47D9-4850-BFF4-1F414E41B507, "MSALErrorDescriptionKey": User interaction is required]

**Comment by wangxiaoms** [comment]
Hi that would mean user needs to sign in interactively and provide consent first.
https://learn.microsoft.com/en-us/entra/identity-platform/tutorial-v2-ios#acquire-tokens

**Comment by redPanda0147** [comment]
Hi @wangxiaoms 

I have integrated the interactive sign-in method, it give me details of the user with the help of graph API. But i don't know about the consent that you are talking about. I read the link provided by you. Is it a settings which I need to perform at portal.azure site?

**Comment by wangxiaoms** [comment]
Hi, please logout the user, and do a refresh interactive login, also make sure to give your app access to the Intune Mobile App Management service:
https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-get-started#give-your-app-access-to-the-intune-mobile-app-management-service

**Comment by redPanda0147** [comment]
Hi, @wangxiaoms 

Thanks for the solution, now its working. I am closing the issue.
