### ISSUE TITLE
V19.4.0 Intune iOS MAM SDK: Failed to connect to location service to determine the user endpoint see the error object for details 

### ISSUE THREAD

**Issue by AnilGit-stack** [microsoftconnect/ms-intune-app-sdk-ios#445]
# Microsoft Intune App SDK for MAUI.iOS Issue

## Summary
Recently updated to Intune V19.4.0 (from 16.0.5)
We did have about 10 enrolled users successful with this app in question built for intune.
Currently next 3 person's enrolled have consistent failure.
It is working for me and others my team but not working for clients 
.

**Intune App SDK for iOS (please complete the following information):**
- For errors during build, does the app build without Intune SDK integration?:  No
- For errors post build, does the app launch without being Intune SDK integrated?: No

- Do you see a trend with it only being reproduced on a specific device? yes

## Details

- Device: [e.g. iPhone 14]
- iOS Version: [e.g. iOS 16.6.1]
- `Microsoft.Intune.Maui.Essentials.iOS` Version: 19.4.0 

## Screenshots and logs
![image](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/assets/117595261/641a1b82-c5c8-405c-86f4-e4b730b2cf35)

## Questions to Ask Before Submission

1. Does the app build and launch without including the `Microsoft.Intune.Maui.Essentials.iOS` package? NO
2. Does the issue reproduce if you rebuild after deleting the `bin` and `obj` output folders? Not tried
3. Have you checked the [.NET MAUI repository](https://github.com/dotnet/maui/issues) for similar issues? If so, please follow the guidance there or add that information to this issue. 
4. Are you using the latest `Microsoft.Intune.Maui.Essentials.iOS` NuGet package version? yes

**Comment by ChismanRaheem** [comment]
Hi @AnilGit-stack please gather verbose logs and app logs for a device that is failing and confirm if any conflicting policy is being applied for the user.
 
**Ref:**
1. https://learn.microsoft.com/en-us/mem/intune/apps/manage-microsoft-edge#use-microsoft-edge-for-ios-and-android-to-access-managed-app-logs
2.  https://learn.microsoft.com/en-us/mem/intune/user-help/send-logs-to-microsoft-ios#share-diagnostic-logs
3. https://learn.microsoft.com/en-us/mem/intune/user-help/retrieve-ios-app-logs

**Comment by ChismanRaheem** [comment]
Hi @AnilGit-stack there has been no actions for over 30 days. I will be archiving this case but if you are still experiencing issues, please reach by respond to this thread with the requested data and my team and I will continue efforts as needed.
