### ISSUE TITLE
UIDocumentInteractionController not changing to accommodate Send org data to other Apps set to Policy Managed

### ISSUE THREAD

**Issue by bmalumphy** [microsoftconnect/ms-intune-app-sdk-ios#447]
**Describe the bug:**
The share sheet in our implementation of UIDocumentInteractionController is not changing in the manner outlined in the docs here, even with all the changes listed in the requirements:

[Documentation Link in Question](https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-ios-phase4#share-data-via-uiactivityviewcontroller)

The app also crashes in the normal, everyday share sheet when trying to Copy.

Our SHARE_EXTENSION_SUBQUERY:

```
SUBQUERY (
				  extensionItems, 
				  $extensionItem,
				  SUBQUERY (
					  $extensionItem.attachments, 
					  $attachment,
					   ANY $attachment.registeredTypeIdentifiers UTI-CONFORMS-TO "public.image" ||
					   ANY $attachment.registeredTypeIdentifiers UTI-CONFORMS-TO "public.movie" ||
					   ANY $attachment.registeredTypeIdentifiers UTI-CONFORMS-TO "public.video" ||
					   ANY $attachment.registeredTypeIdentifiers UTI-CONFORMS-TO "public.mpeg-4-audio" ||
					   ANY $attachment.registeredTypeIdentifiers UTI-CONFORMS-TO "public.aiff-audio" ||
					   ANY $attachment.registeredTypeIdentifiers UTI-CONFORMS-TO "public.aifc-audio" ||
					   ANY $attachment.registeredTypeIdentifiers UTI-CONFORMS-TO "com.adobe.pdf" ||
					   ANY $attachment.registeredTypeIdentifiers UTI-CONFORMS-TO "com.microsoft.intune.mam.public.image" ||
					   ANY $attachment.registeredTypeIdentifiers UTI-CONFORMS-TO "com.microsoft.intune.mam.public.movie" ||
					   ANY $attachment.registeredTypeIdentifiers UTI-CONFORMS-TO "com.microsoft.intune.mam.public.video" ||
					   ANY $attachment.registeredTypeIdentifiers UTI-CONFORMS-TO "com.microsoft.intune.mam.public.mpeg-4-audio" ||
					   ANY $attachment.registeredTypeIdentifiers UTI-CONFORMS-TO "com.microsoft.intune.mam.public.aiff-audio" ||
					   ANY $attachment.registeredTypeIdentifiers UTI-CONFORMS-TO "com.microsoft.intune.mam.public.aifc-audio" ||
					   ANY $attachment.registeredTypeIdentifiers UTI-CONFORMS-TO "com.microsoft.intune.mam.com.adobe.pdf"
					).@count == $extensionItem.attachments.@count
					).@count == 1
```

Our APP:
![image](https://github.com/microsoftconnect/ms-intune-app-sdk-ios/assets/28659220/adead9f3-cd17-49aa-8c94-40ce86d3883a)
![image](https://github.com/microsoftconnect/ms-intune-app-sdk-ios/assets/28659220/8d660eb1-231f-48d4-a926-4995199f113d)

Our CFBundleURLSchemes:

```
MyApp
MyApp-intunemam
msauth.com.my.app.intune, 
msauth.com.my.app.intune-intunemam,
msauth.com.microsoft.intunemam
```

**To Reproduce**
1. Implement the changes to the app necessary in the documentation
2. Map onto our APP configuration
3. Share an item from the app
4. See that the sheet is the same as any other app that isn't managed by InTune

**Expected behavior:**
The share sheet should reflect `only manage apps`

**Screenshots and logs:**
![IMG_0016](https://github.com/microsoftconnect/ms-intune-app-sdk-ios/assets/28659220/78bf9418-4d5c-466c-b94f-2dc6f4a942b8)

[IntuneMAMDiagnosticFiles.txt](https://github.com/user-attachments/files/15855332/IntuneMAMDiagnosticFiles.9.txt)

**Smartphone (please complete the following information):**
 - Device: All iOS Devices

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version? `Latest Version`
- What platform is your app based in (native, Xamarin based, Cordova, etc)? `Native`
- For errors during build, does the app build without Intune SDK integration? `N/A`
- For errors post build, does the app launch without being Intune SDK integrated? `App Cannot be launched without Intune Integrated`

- Who is the customer? `Several Institutional level entities in worldwide government and police work`
- Do you see a trend with it only being reproduced on a specific device? `No`

**Additional context:**
There is an additional crash when copying as mentioned above, and when we do try to share into managed apps, like `MS Teams`, the image/video/etc will not transfer into the app.

**Comment by wangxiaoms** [comment]
Hi @bmalumphy could you provide a minimal sample app, I can test to reproduce.

**Comment by bmalumphy** [comment]
> Hi @bmalumphy could you provide a minimal sample app, I can test to reproduce.

I'll get on to you by EoD
