### ISSUE TITLE
Regarding the issue where the installation stops midway

### ISSUE THREAD

**Issue by tetsuhiro-h** [microsoftconnect/ms-intune-app-sdk-ios#449]
**Describe the bug:**
 I am developing an iOS app, and I have recently updated the IntuneSDK from version 16.0.0 to 19.4.0. However, after this update, we have encountered an issue where users who install the app from the Intune portal experience a prolonged "pending" installation status. In some cases, this status lasts for several hours or even over a day. I would greatly appreciate any insights or solutions regarding the cause of this issue. Thank you.
**Smartphone (please complete the following information):**
 - Device: [e.g. iPhoneSE]
 - OS: [e.g. iOS16,iOS17]

**Comment by wangxiaoms** [comment]
Hi if the issue is at app installation stage it is unlikely related to SDK version, would you provide more details of the installation procedure and the reason you would think it is related to SDK version?

**Comment by tetsuhiro-h** [comment]
Thank you,　wangxiaoms.
 The installation procedure is to press the install button from the "Portal" app as it is an EMS terminal.
 The reason I think it's related to the SDK version is because the issue has been occurring since I updated the SDK version to 19.4.0.

**Comment by wangxiaoms** [comment]
Hi @tetsuhiro-h to trouble shoot the installation procedure, please open a support case with Intune team. It is unlikely SDK version issue unless there is direct evidence we can check.
https://learn.microsoft.com/en-us/mem/get-support
