### ISSUE TITLE
Error in importing IntuneMAMSwift

### ISSUE THREAD

**Issue by Shwethamugeraya** [microsoftconnect/ms-intune-app-sdk-ios#452]
**Describe the bug:**

Failed to build module 'IntuneMAMSwift'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5)', while this compiler is 'Apple Swift version 6.0 effective-5.10 (swiftlang-6.0.0.4.52 clang-1600.0.21.1.3)'). Please select a toolchain which matches the SDK.

**To Reproduce**
Import IntuneMAMSwift in Xcode 16 beta 2

**Expected behavior:**
IntuneMAMSwift should work with X code16beta2
**Screenshots and logs:**

<img width="913" alt="Screenshot 2024-07-03 at 4 02 42 PM" src="https://github.com/microsoftconnect/ms-intune-app-sdk-ios/assets/26622227/4114da04-12e9-4810-9490-616d4389b46b">

**Intune App SDK for iOS (please complete the following information):**

- What version of the Intune SDK are you using? Are you using the latest version? : **'17.3.2'** Even in latest version also issue is observed.

**Comment by wangxiaoms** [comment]
Hi as you can see from the bottom of below page the supported Xcode version is 15.
https://github.com/microsoftconnect/ms-intune-app-sdk-ios

**Comment by Shwethamugeraya** [comment]
Thanks @wangxiaoms. So SDK is not supported for Xcode16 and when are you planning to add the support ?

**Comment by wangxiaoms** [comment]
You can see from below link, although up to change
https://github.com/microsoftconnect/ms-intune-app-sdk-ios/discussions/421
> The upcoming Xcode16 releases (SDK version 20.x) which start in September 2024 will ...
