### ISSUE TITLE
Migrating from Deprecating UPN based APIs

### ISSUE THREAD

**Issue by jukemoon** [microsoftconnect/ms-intune-app-sdk-ios#454]
**Describe the bug:**
When migrating away from the API listed below, I observed that the argument passed to `accountId` is being transferred over to Authenticator as the default value instead of the expected UPN for signing in.

**To Reproduce**
Instead of `- (void) remediateComplianceForIdentity:(NSString*_Nonnull) identity silent:(BOOL) silent;`, use the ObjectId API, `- (void) remediateComplianceForAccountId:(NSString*_Nonnull) accountId silent:(BOOL) silent;`.

**Expected behavior:**
The expected behavior is for the user's UPN/email address should be auto-populated within Authenticator. Instead, the Account ID is being auto-populated.

**Screenshots and logs:**
### Before
`- (void) remediateComplianceForIdentity:(NSString*_Nonnull) identity silent:(BOOL) silent;`  
![identity](https://github.com/microsoftconnect/ms-intune-app-sdk-ios/assets/96348564/920cebf9-41c0-4278-b164-1e9ce7e0af51)

### After
`- (void) remediateComplianceForAccountId:(NSString*_Nonnull) accountId silent:(BOOL) silent;`  
![accountId](https://github.com/microsoftconnect/ms-intune-app-sdk-ios/assets/96348564/388c2170-b49d-41c0-9ce4-c0f38fe55abc)

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: 17.5.1

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version? 
[19.5.0](https://github.com/microsoftconnect/ms-intune-app-sdk-ios/releases/tag/19.5.0), the latest version.

- What platform is your app based in (native, Xamarin based, Cordova, etc)?
Native.

- Do you see a trend with it only being reproduced on a specific device?
No.

**Additional context:**
I posted [a comment](https://github.com/microsoftconnect/ms-intune-app-sdk-ios/discussions/421#discussioncomment-10002286) last week on https://github.com/microsoftconnect/ms-intune-app-sdk-ios/discussions/421. However, since I haven't heard back, I'm opening a separate issue. How should I proceed with the new APIs in instances when I want the UPN to be the default value populated in Authenticator instead of the Account ID?

Thank you in advance!

**Comment by wangxiaoms** [comment]
Hi could you provide,
1. The code snippet where you call remediateComplianceForAccountId, especially how you get the accountId.
2. Is the user already logged in before calling remediateComplianceForAccountId? can you share the code to handle user login, asssume with MSAL.
3. The MAM logs https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-ios-appendix#how-can-i-troubleshoot-my-app

**Comment by jukemoon** [comment]
> Hi could you provide,
> 
> 1. The code snippet where you call remediateComplianceForAccountId, especially how you get the accountId.
> 2. Is the user already logged in before calling remediateComplianceForAccountId? can you share the code to handle user login, asssume with MSAL.
> 3. The MAM logs https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-ios-appendix#how-can-i-troubleshoot-my-app

Hello, @wangxiaoms. After additional testing, Authenticator is mapping the account identifier with their UPN. So, passing the account identifier is working as expected. If any further issues arise, I'll reopen this issue. Thank you for your time.
