### ISSUE TITLE
application:didFinishLaunchingWithOptions possibly not getting called or Intune conflict with Firebase

### ISSUE THREAD

**Issue by JonathanFuentesF** [microsoftconnect/ms-intune-app-sdk-ios#458]
**Describe the bug:**
Hi! We've been receiving crash reports from our users that the application immediately crashes after installing Intune policies and app restart, after that... user's can't open app.

This is only affecting some users, app works as expected for everyone else.
We are unable to reproduce the issue on our end, tested with multiple devices, accounts.

Notes of investigation:
The corresponding crash report shows that application is crashing because we are trying to use firebase remote configuration before being initialized which is done in App Delegate (FirebaseApp.configure())

The first usage of Firebase SDK is in view did load method of the initial view controller of the application which is setup using plist key "Main storyboard file base name"

What are the odds that the view controller is initialized before app did finish launching with options ? or that app did finish launching with options is skipped all together?

This is a UIKit application, we are not using Scene Delegate.

We did a test removing usage of RemoteConfiguration in the app and the app is not crashing anymore for our affected users.

Not sure if this means anything but all reports are from PRO and PRO MAX devices.

**To Reproduce**
1. Go trough the login flow
2. Intune install policies
3. App Restarts
4. App immediately crashes after opening.

**Expected behavior:**
App Doesn't crash after installing policies restart.

**Screenshots and logs:**
- If applicable, add screenshots to help explain your problem. 
- If your app is experiencing an issue during build, do you have app logs for the crash itself? 
- If your app is experiencing an issue post build, do you have app logs for the crash itself?

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version? - 19.5.0
- What platform is your app based in (native, Xamarin based, Cordova, etc)? - Native
- For errors post build, does the app launch without being Intune SDK integrated? - Yes

- Who is the customer?
- Do you see a trend with it only being reproduced on a specific device?
Reports only show PRO and PRO MAX
![Screenshot 2024-07-25 at 3 30 11 PM](https://github.com/user-attachments/assets/e8df2e1a-e6d5-4f8b-a5c0-2baf714f03d3)
![Screenshot 2024-07-25 at 3 26 24 PM](https://github.com/user-attachments/assets/696428be-6b7b-492f-95a6-ac23c6fd0cbd)
![Screenshot 2024-07-25 at 3 26 09 PM](https://github.com/user-attachments/assets/eed15a51-142f-44c8-bdc5-f6551dc5a59a)

**Comment by wangxiaoms** [comment]
Hi can you get the crash report, ips file, send to me wangxiao@microsoft.com
https://developer.apple.com/documentation/xcode/diagnosing-issues-using-crash-reports-and-device-logs

**Comment by JonathanFuentesF** [comment]
@wangxiaoms report has been sent.

**Comment by wangxiaoms** [comment]
As discussed via email please add IntuneMAMSettings with related paramters.

**Comment by wangxiaoms** [comment]
Hi @JonathanFuentesF is there any update?

**Comment by wangxiaoms** [comment]
As discussed in email I'm closing the issue.

>_We are not able to reproduce our error internally so not sure if it works, affected users were provided a build that moves Firebase initialization after appDidFinishLaunchingwithOptions and this worked even though I prefer your solution as a fix to be able to return Firebase initialization back to its original place._

>_It is not possible for us to do testing with affected users since it is production so I guess we can mark the issue as fixed.
We’ll include your solution (FinishLaunchingAtStartup to true in Info.plist) anyway just in case._
