### ISSUE TITLE
"The operation could not be completed because the user is not licensed for MAM" even though user is assigned an Intune license in Entra

### ISSUE THREAD

**Issue by lukeashton4** [microsoftconnect/ms-intune-app-sdk-ios#459]
**Describe the bug:**
After running registerAndEnrollAccountId(...), an idToken is presented and the sign-in window is closed taking the user back to the app page. After this, the user sees an error which says "Error Authenticating - There was an error while logging you into your account. Please check your log in credentials and try again.". Upon checking the logs in enrollmentRequest(), status.didSucceed is false, status.statusCode is 200, and status.errorString is "The operation could not be completed because the user is not licensed for MAM". This appears to be wrong as the user is definitely licensed for Intune through Microsoft Entra. This is happening on iOS only - it seems to work without problem for the same user on Android.

This issue is temperamental. Sometimes it appears and sometimes it does not. I believe this is based on whether the current user is already enrolled on the device. However, when the error doesn't appear, the app lingers on our loading page as the result is never returned from the code below:
![image](https://github.com/user-attachments/assets/5664c2b0-ffb8-4dfe-b184-94a127cf4b3c)

The app doesn't seem to get past this block of code:
![image](https://github.com/user-attachments/assets/ea9367db-3d25-446d-bc63-8d6dee89b4cc)

**To Reproduce**
1. Fresh install of the app from the Apple store, which is using the Intune SDK.
2. Enter email into the app login screen.
3. Now a Microsoft login page opens where the user is prompted to login.
4. After successdully logging in, admin permissions need to be granted for the Enterprise Application in Entra - this is done and permissions can be seen in Entra.
5. User is redirected back to the app.
6. Error pops up: "Error Authenticating - There was an error while logging you into your account. Please check your log in credentials and try again.".
7. When the error above doesn't appear, the app just spins as it is waiting for a result back from IntuneAppDelegate.checkEnrolledAccount();

**Expected behavior:**
I would expect the user to be taken through enrolment, and successfully logged in.

**Screenshots and logs:**
![image](https://github.com/user-attachments/assets/3838e2a6-fe85-4f1a-b712-3f8ee3316e9a)

Gets here and runs this in MSALManager.swift - logs "Intune register function done":
![image](https://github.com/user-attachments/assets/fa9d9bea-2116-42dd-9888-6786133cb207)

<img width="898" alt="image" src="https://github.com/user-attachments/assets/45e642f7-a911-432e-a7fb-68fd07d6ba5c">

**Smartphone (please complete the following information):**
 - Device: iPhone 15 Pro Max
 - OS: iOS 17.0

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version?
18.0.0

- What platform is your app based in (native, Xamarin based, Cordova, etc)?
React Native with Intune SDK integrated with swift:
![image](https://github.com/user-attachments/assets/33f1e2ac-6337-48be-96d0-e7a4bef58677)
![image](https://github.com/user-attachments/assets/87eac238-a990-4452-993e-a90f6ad19731)

- For errors during build, does the app build without Intune SDK integration? N/A
- For errors post build, does the app launch without being Intune SDK integrated? N/A

- Who is the customer?
We are able to reproduce locally, but this is also happening for live customers.

- Do you see a trend with it only being reproduced on a specific device.
iOS only.

**Additional context:**

**Comment by wangxiaoms** [comment]
Hi is the issue happening to all users or a small number of them? What is the Intune license assigned to the user having the problem?

**Comment by lukeashton4** [comment]
Hi @wangxiaoms - this was happening for all users. I have managed to resolve the issue - it was being caused by calling enrolAccountAndLogin() after initial login. This can be closed. Thanks
