### ISSUE TITLE
Conditional Access failure at large Intune customer on all iOS devices

### ISSUE THREAD

**Issue by fowlerp-qlik** [microsoftconnect/ms-intune-app-sdk-ios#461]
I addressed the comment in https://github.com/microsoftconnect/ms-intune-app-sdk-ios/issues/455 but upgrading the iOS Intune SDK to version 17.7.6. ADAL version is 4.0.7. Customer has conditional access rule with a compliancy requirement: device must be enrolled. When attempting to authenticate via MS Authenticator an error is presented that the conditional access rule is not 
satisfied. The details in the image screenshot attached imply that the device is not enrolled but it really is. 

**To Reproduce**
1. Launch our Intune/Adal enabled app 
2. Attempt to authenticate via MS Authenticator

**Expected behavior:**
A screen appears showing that the conditional access rule is not satisfied. See movie. 

**Screenshots and logs:**
- image attached showing error presented to user. Notice device state and device identifier values.
- Intune Logs attached

**Smartphone (please complete the following information):**
 - Device: iPad
 - OS: 17.x

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? 17.7.6, ADAL 4.0.7
- What platform is your app based in: objective C 
- For errors during build, does the app build without Intune SDK integration? No build errors
- For errors post build, does the app launch without being Intune SDK integrated? Yes

- Who is the customer? Large insurance company in India
- Almost all devices. This is a report that that one works but that has not been confirmed

**Additional context:**
In the Intune startup logs I see

2024-08-03T10:19:06.117Z        INFO    com.qlik.qliksense.mobile       tid=4       id=(nil),ui=(nil),io=(nil)           IntuneMAM: CMARManagementUtils: No enrolled user present from the Company Portal.
2024-08-03T10:19:06.117Z        INFO    com.qlik.qliksense.mobile       tid=4       id=(nil),ui=(nil),io=(nil)           IntuneMAM: CMARManagementUtils: Checking presence SSO extensions
2024-08-03T10:19:06.117Z        INFO    com.qlik.qliksense.mobile       tid=4       id=(nil),ui=(nil),io=(nil)           IntuneMAM: CMARManagementUtils: MDM Certificate is not found and no presence of SSO extensions, device is not MDM enrolled.

even though the device is enrolled. Our app is receiving app configuration policy configuration data.

[Intune-com.qlik.qliksense.mobile-0.txt](https://github.com/user-attachments/files/16560577/Intune-com.qlik.qliksense.mobile-0.txt)
[IntuneMAMDiagnosticInfo.txt](https://github.com/user-attachments/files/16560578/IntuneMAMDiagnosticInfo.txt)
![image](https://github.com/user-attachments/assets/d9a6e6a5-b27e-4409-8876-764caddd15ec)

**Comment by fowlerp-qlik** [comment]
Today's testing with the customer was much better. If the customer first deleted the old app from the iOS device then installed the new app there was success (on four different iOS devices).

**Comment by wangxiaoms** [comment]
Hi ADAL has been deprecated, It is recommended to migrate from ADAL to MSAL, also recommend to upgrade Intune SDK to latest version.
https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-ios-phase2#what-about-adal

**Comment by fowlerp-qlik** [comment]
ok. For planning purposes when will ADAL stop working?

**Comment by wangxiaoms** [comment]
_Starting, June 30th, 2023, we will end support for ADAL and Azure AD Graph and will no longer provide technical support or security updates. Apps using Azure AD Graph after this time will no longer receive responses from the Azure AD Graph endpoint. Apps using ADAL on existing OS versions will continue to work after this time but will not get any technical support or security updates._
https://techcommunity.microsoft.com/t5/microsoft-entra-blog/update-your-applications-to-use-microsoft-authentication-library/ba-p/1257363
