### ISSUE TITLE
Upgrading to 19.6 causes didFinishLaunchingWithOptions to stop working

### ISSUE THREAD

**Issue by chasemac** [microsoftconnect/ms-intune-app-sdk-ios#463]
**To Reproduce**
1. Upgrade from 19.4 to 19.6
2. Set a breakpoint in didFinishLaunchingWithOptions inside the AppDelegate
3. Breakpoint will not hit

**Expected behavior:**
Breakpoint hits in didFinishLaunchingWithOptions

**Smartphone (please complete the following information):**
 - Device: iPhone
 - OS: 17.5

**Intune App SDK for iOS (please complete the following information):**
- 19.6.0
- Native

**Additional context:**
My app is a SwiftUI app with set up similar to this example: https://www.hackingwithswift.com/quick-start/swiftui/how-to-add-an-appdelegate-to-a-swiftui-app

**Comment by chasemac** [comment]
is this related to: https://github.com/microsoftconnect/ms-intune-app-sdk-ios/issues/458

Also in [19.6](https://github.com/microsoftconnect/ms-intune-app-sdk-ios/releases/tag/19.6.0) release notes it says: "Fixed a bug where some APIs on Swift UI app delegates wouldn't get called."
It appears the opposite is true.

**Comment by wangxiaoms** [comment]
Hi could you provide a minimal sample that can reproduce the issue.

**Comment by chasemac** [comment]
The company I work for doesn't pay me to do Microsoft QA work. Do I need to create a support ticket to get Microsoft to have someone QA this?

**Comment by wangxiaoms** [comment]
Hi you don't need to create support ticket for this one, we are looking into it.

**Comment by wangxiaoms** [comment]
@chasemac Issue is fixed in version 19.7.0 
https://github.com/microsoftconnect/ms-intune-app-sdk-ios/releases/tag/19.7.0
