### ISSUE TITLE
MAM Background Blur Snapshot Screen Issue

### ISSUE THREAD

**Issue by LibertyDev18** [microsoftconnect/ms-intune-app-sdk-ios#465]
**Issue:**
When an app integrated with the latest version of the SDK (19.6.0) is backgrounded it will _sometimes_ display a blurred snapshot screen that is half black and half scrambled up. In previous versions of the SDK it would consistently show a fully blurred snapshot screen as expected.

19.6.0 release notes indicate there were some changes with blurred views and am curious if this is maybe related to that change being that 19.6.0 is the first time we are seeing this.

Attaching a screenshot of the scrambled snapshot screen for reference.

**To Reproduce**
1. Upgrade Intune SDK to 19.6.0
2. After successful app management move the app into the background
3. View the blurred background snapshot screen
4. Screen is scrambled in the background and when foregrounding waiting for biometrics to unlock

**Expected behavior:**
Smooth blurred snapshot screen not split in half with only black background

**Screenshots and logs:**
- Screenshot attached

**Smartphone (please complete the following information):**
 - Device: All iPhone models
 - OS: iOS 17.6.1

**Intune App SDK for iOS (please complete the following information):**
- Intune SDK 19.6.0
- Native app
- No errors logged

![scrambled_background_blur_screenshot2](https://github.com/user-attachments/assets/cd3458b9-16cd-45d1-86df-94f6d7b875de)

**Comment by wangxiaoms** [comment]
Hi would you provide a minimal sample app that can reproduce the issue. So far I do not see this in my tests.

**Comment by wangxiaoms** [comment]
Can you try the latest SDK version 19.7.0
https://github.com/microsoftconnect/ms-intune-app-sdk-ios/releases/tag/19.7.0

**Comment by LibertyDev18** [comment]
Hi @wangxiaoms, it does look like 19.7.0 resolves the issue. Thank you!
