### ISSUE TITLE
Getting 'MSALDomain error -50000' error, post integration of Intune SDK in our app

### ISSUE THREAD

**Issue by shivcelumula** [microsoftconnect/ms-intune-app-sdk-ios#467]
**Describe the bug:**
I have integrated Intune SDK into our app. Followed all the steps in the guide (https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-ios-phase3). 
- When I run the app, it prompts with our SSO login (which wasn't happening previously).
- Post successful SSO login, getting attached error

**To Reproduce**
1. Run the app
2. Enter work Id credentials
3. Login is successful

**Expected behavior:**
App should be authenticated and should prompt login screen (Salesforce login screen) of our app.

**Screenshots and logs:**
![Screenshot 2024-09-11 at 16 54 15](https://github.com/user-attachments/assets/27597c61-06ff-4126-814f-ac76d132eae5)
![Screenshot 2024-09-11 at 16 45 59](https://github.com/user-attachments/assets/b2d7756c-df0a-43c4-85a2-79bffa8d7ee8)
![Screenshot 2024-09-11 at 15 29 41](https://github.com/user-attachments/assets/0aac9714-3263-459a-acf6-dcbdf770220e)

Console logs : container_create_or_lookup_app_group_path_by_app_group_identifier: client is not entitled

**Smartphone (please complete the following information):**
 - Device: iPhone Simulator - iPhone15 Pro Max
 - OS: iOS 17.2

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version? Yes, 19.6.0
- What platform is your app based in (native, Xamarin based, Cordova, etc)? native
- For errors during build, does the app build without Intune SDK integration? Yes
- For errors post build, does the app launch without being Intune SDK integrated? Yes

- Who is the customer? Johnson and Johnson
- Do you see a trend with it only being reproduced on a specific device? No, happens on all the simulators

**Additional context:**
Our app was embedded with Salesforce SDK, which we use for login and data operations.

**Comment by wangxiaoms** [comment]
Hi can you remove ADALRedirectScheme since you already have ADALRedirectUri.

**Comment by shivcelumula** [comment]
Hi @wangxiaoms , removed ADALRedirectScheme and still same error..

**Comment by wangxiaoms** [comment]
Can you get MAM logs 
https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-ios-appendix#how-can-i-troubleshoot-my-app

**Comment by shivcelumula** [comment]
Added the line IntuneMAMDiagnosticConsole.display() in AppDelegate, and got below screen for enabling logs, but unable to see Monitor in admin centre. 
<img width="704" alt="Screenshot 2024-09-13 at 17 25 54" src="https://github.com/user-attachments/assets/29369aee-70a7-4e9a-b820-508c7e58ec01">

<img width="272" alt="Screenshot 2024-09-13 at 17 19 51" src="https://github.com/user-attachments/assets/1c5d1903-09e7-4c59-8080-826aa03881e9">

**Comment by wangxiaoms** [comment]
From the logs MSAL seems is not correctly linked, can you:
1. Link MSAL to Your Project: https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-ios-phase2#link-msal-to-your-project
2. Use Intune SDK version 19.7.0: https://github.com/microsoftconnect/ms-intune-app-sdk-ios/releases/tag/19.7.0

**Comment by shivcelumula** [comment]
Hi @wangxiaoms,

Followed the instructions and configured latest Intune SDK 19.7.0 into the code. And app's behaving like before(as shown in the video), don't see any changes. Do we need to see something after integration..? How to verify the integration..?

https://github.com/user-attachments/assets/723ffedd-2e07-4e54-aa6e-6169f60dc879

**Comment by wangxiaoms** [comment]
The video does not show any login procedure or error?

**Comment by shivcelumula** [comment]
Yes, if I don't put any code in AppDelegate, it doesn't show any login process, but if I try to add below code, I get the login screen as shown :

                let manager = IntuneMAMEnrollmentManager.instance()
                manager.delegate = self
                manager.loginAndEnrollAccount(nil)


https://github.com/user-attachments/assets/84272ff8-8b41-4c74-9236-df9203b048ba

**Comment by wangxiaoms** [comment]
loginAndEnrollAccount should not be called in AppDelegate. As a first step to integrate Intune SDK, can you get below sample app working, it already has MSAL integrated, can you test and get it working.
https://github.com/microsoftconnect/Chatr-Sample-Intune-iOS-App

**Comment by shivcelumula** [comment]
Hi @wangxiaoms 
Made changes to the sample app with our app credentials and looks like it's working.
https://github.com/user-attachments/assets/90d823a8-1a5a-4566-be6d-e7ec0d0bb067

**Comment by wangxiaoms** [comment]
> Hi @wangxiaoms Made changes to the sample app with our app credentials and looks like it's working. So, do I need to mimic the same to our app..? https://github.com/user-attachments/assets/90d823a8-1a5a-4566-be6d-e7ec0d0bb067

Yes you can follow the sample app to get your app working.

**Comment by shivcelumula** [comment]
Hi @wangxiaoms , 

After adding necessary API permissions and MAM policies to the app, looks like the authentication is happening. But app is crashing post authentication, while showing the Salesforce login page, as our app was integrated with Salesforce iOS SDK for login and data operations. Below is the log : 

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIApplication session]: unrecognized selector sent to instance 0x109e07590'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007ff80049b761 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007ff800063904 objc_exception_throw + 48
	2   CoreFoundation                      0x00007ff8004b0873 +[NSObject(NSObject) instanceMethodSignatureForSelector:] + 0
	3   UIKitCore                           0x00007ff805bf2efc -[UIResponder doesNotRecognizeSelector:] + 266
	4   CoreFoundation                      0x00007ff80049fef4 ___forwarding___ + 1459
	5   CoreFoundation                      0x00007ff8004a20f8 _CF_forwarding_prep_0 + 120
	6   SalesforceSDKCore                   0x000000010942e148 -[SalesforceSDKManager handleSceneDidActivate:] + 120
	7   TruView-QA                          0x00000001070824b8 cmarDeviceComplianceEnabled + 527980
	8   TruView-QA                          0x0000000107082699 cmarDeviceComplianceEnabled + 528461
	9   TruView-QA                          0x0000000106ffc5a2 $s14IntuneMAMSwift0aB5ErrorOMa + 71042
	10  TruView-QA                          0x00000001071db9c6 cmarDeviceComplianceEnabled + 1942394
	11  TruView-QA                          0x00000001072d89fa cmarInternalIsDeviceJailbroken + 156083
	12  TruView-QA                          0x00000001072d9304 cmarInternalIsDeviceJailbroken + 158397
	13  TruView-QA                          0x00000001072e0b40 cmarInternalIsDeviceJailbroken + 189177
	14  TruView-QA                          0x00000001072d6142 cmarInternalIsDeviceJailbroken + 145659
	15  TruView-QA                          0x0000000107254771 cmarDeviceComplianceEnabled + 2437413
	16  TruView-QA                          0x000000010725358d cmarDeviceComplianceEnabled + 2432833
	17  TruView-QA                          0x00000001072544b1 cmarDeviceComplianceEnabled + 2436709
	18  TruView-QA                          0x00000001070173ab cmarDeviceComplianceEnabled + 89439
	19  TruView-QA                          0x0000000107255f8d cmarDeviceComplianceEnabled + 2443585
	20  TruView-QA                          0x00000001072d4653 cmarInternalIsDeviceJailbroken + 138764
	21  TruView-QA                          0x00000001072d0c5a cmarInternalIsDeviceJailbroken + 123923
	22  UIKitCore                           0x00007ff805ffb002 -[UITextField keyboardInput:shouldInsertText:isMarkedText:] + 214
	23  UIKitCore                           0x00007ff80594c870 -[UIKeyboardImpl(UIKitInternal) callShouldInsertText:onDelegate:] + 165
	24  UIKitCore                           0x00007ff8058f5bda -[UIKeyboardImpl callShouldInsertText:] + 129
	25  UIKitCore                           0x00007ff80591db71 -[UIKeyboardImpl addWordTerminator:afterSpace:afterAcceptingCandidate:elapsedTime:executionContext:] + 122
	26  UIKitCore                           0x00007ff80591a6c6 __49-[UIKeyboardImpl addInputEvent:executionContext:]_block_invoke + 497
	27  UIKitCore                           0x00007ff805966689 -[UIKeyboardTaskExecutionContext returnExecutionToParentWithInfo:] + 232
	28  UIKitCore                           0x00007ff80591ad5a -[UIKeyboardImpl acceptAutocorrectionForWordTerminator:executionContextPassingTIKeyboardCandidate:] + 762
	29  UIKitCore                           0x00007ff80591a155 -[UIKeyboardImpl addInputEvent:executionContext:] + 997
	30  UIKitCore                           0x00007ff805919ba8 __97-[UIKeyboardImpl addInputString:withFlags:withInputManagerHint:withInputSource:executionContext:]_block_invoke + 439
	31  UIKitCore                           0x00007ff805919933 -[UIKeyboardImpl addInputString:withFlags:withInputManagerHint:withInputSource:executionContext:] + 1313
	32  UIKitCore                           0x00007ff80591940c -[UIKeyboardImpl addInputString:withFlags:withInputManagerHint:executionContext:] + 28
	33  UIKitCore                           0x00007ff80591719a -[UIKeyboardImpl handleStringInput:withFlags:withInputManagerHint:executionContext:] + 271
	34  UIKitCore                           0x00007ff8059403ca -[UIKeyboardImpl handleKeyWithString:forKeyEvent:executionContext:] + 1165
	35  UIKitCore                           0x00007ff8058d9f41 -[UIKeyboardImpl performOperations:withTextInputSource:] + 34
	36  UIKitCore                           0x00007ff80593fa04 -[UIKeyboardImpl handleKeyEvent:executionContext:] + 4316
	37  UIKitCore                           0x00007ff80593e525 __33-[UIKeyboardImpl handleKeyEvent:]_block_invoke + 45
	38  UIKitCore                           0x00007ff8059686dc -[UIKeyboardTaskEntry execute:] + 193
	39  UIKitCore                           0x00007ff805966e66 -[UIKeyboardTaskQueue continueExecutionOnMainThread] + 376
	40  UIKitCore                           0x00007ff805967422 -[UIKeyboardTaskQueue addTask:] + 139
	41  UIKitCore                           0x00007ff80593e4b5 -[UIKeyboardImpl handleKeyEvent:] + 373
	42  CoreFoundation                      0x00007ff8004a238c __invoking___ + 140
	43  CoreFoundation                      0x00007ff80049f6b3 -[NSInvocation invoke] + 302
	44  UIKitCore                           0x00007ff8060cea4b -[UIRepeatedAction invoke] + 265
	45  UIKitCore                           0x00007ff8060ceccd -[UIRepeatedAction _preInvocationTimerFire] + 70
	46  UIKitCore                           0x00007ff805bdedfc -[UIApplication _handleKeyboardPressEvent:] + 3335
	47  UIKitCore                           0x00007ff805bc5dc9 -[UIApplication pressesBegan:withEvent:] + 403
	48  UIKitCore                           0x00007ff805bf19ab forwardTouchMethod + 311
	49  UIKitCore                           0x00007ff805bf19ab forwardTouchMethod + 311
	50  UIKitCore                           0x00007ff805bf19ab forwardTouchMethod + 311
	51  UIKitCore                           0x00007ff805bf19ab forwardTouchMethod + 311
	52  UIKitCore                           0x00007ff805bf19ab forwardTouchMethod + 311
	53  UIKitCore                           0x00007ff805bf19ab forwardTouchMethod + 311
	54  UIKitCore                           0x00007ff805bf19ab forwardTouchMethod + 311
	55  UIKitCore                           0x00007ff805bf19ab forwardTouchMethod + 311
	56  UIKitCore                           0x00007ff8061efefc -[UIScrollView pressesBegan:withEvent:] + 188
	57  UIKitCore                           0x00007ff805bf19ab forwardTouchMethod + 311
	58  UIKitCore                           0x00007ff805bf19ab forwardTouchMethod + 311
	59  UIKitCore                           0x00007ff805bf19ab forwardTouchMethod + 311
	60  UIKitCore                           0x00007ff805feac1b -[UITextField pressesBegan:withEvent:] + 377
	61  UIKitCore                           0x00007ff805c057d5 -[UIWindow _sendButtonsForEvent:] + 489
	62  UIKitCore                           0x00007ff805c06b70 -[UIWindow sendEvent:] + 4095
	63  UIKitCore                           0x00007ff805bdc010 -[UIApplication sendEvent:] + 772
	64  UIKitCore                           0x00007ff805bdd646 -[UIApplication _handleKeyUIEvent:] + 573
	65  UIKitCore                           0x00007ff805bf615e -[UIResponder _handleKeyUIEvent:] + 76
	66  UIKitCore                           0x00007ff805bf615e -[UIResponder _handleKeyUIEvent:] + 76
	67  UIKitCore                           0x00007ff805bf615e -[UIResponder _handleKeyUIEvent:] + 76
	68  UIKitCore                           0x00007ff805bf615e -[UIResponder _handleKeyUIEvent:] + 76
	69  UIKitCore                           0x00007ff805bf615e -[UIResponder _handleKeyUIEvent:] + 76
	70  UIKitCore                           0x00007ff805bf615e -[UIResponder _handleKeyUIEvent:] + 76
	71  UIKitCore                           0x00007ff805bf615e -[UIResponder _handleKeyUIEvent:] + 76
	72  UIKitCore                           0x00007ff805bf615e -[UIResponder _handleKeyUIEvent:] + 76
	73  UIKitCore                           0x00007ff805bf615e -[UIResponder _handleKeyUIEvent:] + 76
	74  UIKitCore                           0x00007ff805bf615e -[UIResponder _handleKeyUIEvent:] + 76
	75  UIKitCore                           0x00007ff805bf615e -[UIResponder _handleKeyUIEven
libc++abi: terminating due to uncaught exception of type NSException


Also raised a ticket to SalesforceMobileSDK support team, to get their insights:
https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/3763

**Comment by wangxiaoms** [comment]
@shivcelumula from the issue https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/3763 it is working now?

**Comment by shivcelumula** [comment]
Yes @wangxiaoms , looks like it is working, but I kept this issue open to check if it is working in other environments too. I'll do that tomorrow and let you know. Thanks

**Comment by shivcelumula** [comment]
Hi @wangxiaoms, 
It is working in all environments, thank you so much for your support. You can close this issue.
