### ISSUE TITLE
Error With App Protection

### ISSUE THREAD

**Issue by dmholmes** [microsoftconnect/ms-intune-app-sdk-ios#469]
We are integrating the SDK into a corporate app and having an issue with app protection. Is there any configuration required outside the app for app protection to work?

Screenshot of error at app launch:
![IMG_0002](https://github.com/user-attachments/assets/c088c6e9-5358-4975-bf25-06f105273de2)

**Comment by kanishkaBagga** [comment]
@dmholmes - It sounds like you're working on integrating the Intune SDK into your iOS app and facing issues with app protection. Here are some key points to consider:

1. App Protection Conditional Access: This feature blocks access to server tokens until Intune confirms that the app protection policy has been applied. This requires changes to your add user flows. Once enabled, applications in the customer's tenant that access protected resources won't be able to acquire an access token unless they support this feature(https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-ios-phase6).

2. **SDK Integration Steps**: To enable the Intune App SDK, you need to link either `IntuneMAMSwift.xcframework` or `IntuneMAMStatic.xcframework` to your target. For your main app, select "Embed & Sign" in the "Embed" column for both the xcframeworks added. For any extensions, select "Do Not Embed." Additionally, add the required iOS frameworks to the project 
Please refer this for more details on steps required 
https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-ios-phase

**Comment by dmholmes** [comment]
@kanishkaBagga thanks for the reply. Yes we have completed the integration steps for the SDK as far as we know. I'm unsure about your first key point, is that done by on the Azure portal by an admin?

**Comment by kanishkaBagga** [comment]
@dmholmes yes, changes are required on the portal

**Comment by dmholmes** [comment]
@kanishkaBagga thank you. I don't have access to our portal but I believe it is done. We are currently getting this error:
<img width="389" alt="image" src="https://github.com/user-attachments/assets/f1be9a86-faf9-45f2-be94-75ce3bb226a3">

**Comment by dmholmes** [comment]
We made a little progress, now we get AADSTS50011 redirect URI msauth.com.microsoft.intunemam://auth does not match application redirect URI. Our application redirect URI specified in IntuneMAMSettings is being ignored.

CFBundleURLSchemes from Info.plist
`<string>ourappscheme</string>
<string>ourappscheme-intunemam</string>
<string>msauth.$(PRODUCT_BUNDLE_IDENTIFIER)</string>
<string>msauth.$(PRODUCT_BUNDLE_IDENTIFIER)-intunemam</string>
<string>msauth.com.microsoft.intunemam</string>
<string>msauth.com.microsoft.intunemam-intunemam</string>`

**Comment by kanishkaBagga** [comment]
@dmholmes Verify Redirect URIs:
Ensure the redirect URI in your IntuneMAMSettings matches exactly with one of the URIs in your Azure app registration.
Update Azure App Registration:
Go to the Azure portal.
Navigate to Azure Active Directory > App registrations.
Select your application.
In the Authentication section, add msauth.com.microsoft.intunemam://auth if it’s not listed.
Check Info.plist:
Ensure CFBundleURLSchemes in Info.plist includes the correct schemes for your app and IntuneMAM.
Wait for Changes to Propagate:
Allow a few minutes for changes in the Azure portal to take effect before testing again.

**Comment by dmholmes** [comment]
@kanishkaBagga sorry I forgot to close this, we found the issue last week. The RedirectUri key in Info.plist is case sensitive and it didn't match.
