### ISSUE TITLE
enrolledAccount() is being deprecated but there's not replacement

### ISSUE THREAD

**Issue by chasemac** [microsoftconnect/ms-intune-app-sdk-ios#470]
I've been using enrolledAccount() to fetch the user's UPN. The suggested replacement doesn't return a UPN.

Any ideas on work arounds? 

How soon will enrolledAccount() be removed?

**Comment by ChismanRaheem** [comment]
HI @chasemac Intune has begun using Entra object ID to identify accounts since it is a true unique account identifier and there are scenarios where multiple accounts may have the same UPN. The enrolledAccount API has already been removed in version 20.x for Xcode 16. App developers can use MSAL APIs to map an OID to a UPM/email address/user-friendly account name. 

Recommendation: 
The API to use would be accountForIdentifier:error: on the MSALPublicClientApplication class: https://github.com/AzureAD/microsoft-authentication-library-for-objc/blob/daaaa67ccecfde0766018654b966be2f2ad6ef7a/MSAL/src/public/MSALPublicClientApplication.h#L204

This will return a MSALAccount object, on which they can query the username property: https://github.com/AzureAD/microsoft-authentication-library-for-objc/blob/daaaa67ccecfde0766018654b966be2f2ad6ef7a/MSAL/src/public/MSALAccount.h#L46

**Comment by chasemac** [comment]
try application.account(forIdentifier: accountId) is returning "nilError"
![IMG_4307](https://github.com/user-attachments/assets/ae3ee395-e270-40c7-846b-15be587ee647)

Any insight on what could be the cause of the error?

**Comment by chasemac** [comment]
I can't post on GitHub from my work laptop, that's why I post pics of the screen from my personal account.

**Comment by AceChen7** [comment]
i have the same issue.... can give more detail how how to use account id to map upn account ?

**Comment by andrejacobs-unily** [comment]
@chasemac Did you ever get resolution on this issue?

I am in the process of upgrading to v20.x of the Intune MAM SDK and also discovering that the .enrolledAccount() method is removed. Which we used to remediate compliance as per requirement when using Conditional Access.

Not sure if you trying to do the same, but maybe this bit in the docs might be of help to you.

https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-ios-phase6#:~:text=To%20fetch%20the,remediation%20API%20remediateComplianceForAccountId.

"To fetch the Entra object ID for the accountId parameter of the MAM SDK compliance remediation APIs you need to do the following:

First get the homeAccountId from userInfo[MSALHomeAccountIdKey] within MSALError object sent back by MSAL when it reports ERROR_SERVER_PROTECTION_POLICY_REQUIRED to the app.
This homeAccountId will be in the format ObjectId.TenantId. Extract the ObjectId value by spliting the string on the '.' and then use that value for the accountId parameter in remediation API remediateComplianceForAccountId."


I am about to find out if this works for us or not.

**Comment by chasemac** [comment]
I never got it working with the solution they gave me. However in the IntuneMAMEnrollmentDelegate the enrollmentRequest(with status: IntuneMAMEnrollmentStatus) returns the users email  from status.identity.
I save that in UserDefaults after that delegate method is called.

**Comment by pa-akiya-ozawa** [comment]
@chasemac 

> I never got it working with the solution they gave me. However in the IntuneMAMEnrollmentDelegate the enrollmentRequest(with status: IntuneMAMEnrollmentStatus) returns the users email from status.identity.
> I save that in UserDefaults after that delegate method is called

Hi, do you know what you did is the best practice written somewhere in the doc?

Thanks in advance.

**Comment by andrejacobs-unily** [comment]
Btw, I found that the v20.x SDKs simply renamed to enrolledAccountId() and mentions it is the Entra ID. Will see how this pans out.

**Comment by pa-akiya-ozawa** [comment]
@ChismanRaheem 

Hi, I've tried what you recommended like below. 
```
 let clientId = "xxxxxx-xxxxx-xxxx-xxx-xxxxx"

 guard let enrolledAccountId = IntuneMAMEnrollmentManager.instance().enrolledAccountId() else { return }
            
 let config = MSALPublicClientApplicationConfig(clientId: clientId)
            
 do {
         let application = try MSALPublicClientApplication(configuration: config)
         let account = try application.account(forIdentifier: enrolledAccountId)
         print(account.username)
       } catch let error {
          print(error) // nilError
       }
```
However, the accountIdentifier method returns nilError.
What are possible causes of this error?

**Comment by ChismanRaheem** [comment]
I recommend using msal tenantProileIdentifier to acquire oid.tid here is an **Example **: 
ref : https://learn.microsoft.com/en-us/dotnet/api/microsoft.identity.client.tenantprofile?view=msal-dotnet-latest

```
import MSAL

let config = MSALPublicClientApplicationConfig(clientId: clientId, redirectUri: redirectUri, authority: authority)
let msalApplication = try? MSALPublicClientApplication(configuration: config)
let parameters = MSALAccountEnumerationParameters(tenantProfileIdentifier: oid)
var error: NSError? = nil
let accounts = msalApplication?.accounts(for: parameters, error: &error)
var upn = ""

if let accounts = accounts {
    for account in accounts {
        upn = account.username
    }
}
```
