### ISSUE TITLE
How to retrieve Intune policies in a Share Extension app?

### ISSUE THREAD

**Issue by bao-nguyen1** [microsoftconnect/ms-intune-app-sdk-ios#471]
Hi,
My regular app uses Intune to retrieve policies from the MDM server and control access based on those policies. The regular app also supports a Share Extension.
In the Share Extension, I want to fetch and access the MDM policies to control access before sharing content, just like in the regular app, but I don't know how to set this up for the Share Extension target.
Can anyone help me?

**Comment by wangxiaoms** [comment]
Hi can you follow below guide for managed and unmanaged device apps 
https://learn.microsoft.com/en-us/mem/intune/apps/data-transfer-between-apps-manage-ios#use-open-in-management-to-protect-ios-apps-and-data
