### ISSUE TITLE
Get Enrolled Account Using AutoEnrollOnLaunch

### ISSUE THREAD

**Issue by dmholmes** [microsoftconnect/ms-intune-app-sdk-ios#475]
We need to get the enrolled account but see that it is deprecated. Is there a way to get this as mentioned in [issue 470](https://github.com/microsoftconnect/ms-intune-app-sdk-ios/issues/470) when letting Intune handle authentication by using  AutoEnrollOnLaunch? We don't have an account from a previous acquireToken() call.

**Comment by chasemac** [comment]
@dmholmes I don't see that method in the latest version of Intune. Can you share more info? I'm stuck right now.

**Comment by dmholmes** [comment]
> @dmholmes I don't see that method in the latest version of Intune. Can you share more info? I'm stuck right now.

You don't have this one?
<img width="553" alt="Screenshot 2024-10-15 at 2 03 06 PM" src="https://github.com/user-attachments/assets/6f35a1bf-37dc-495f-a67b-21c19fd0995e">

**Comment by chasemac** [comment]
Not that one, this one: accountForIdentofier()

**Comment by dmholmes** [comment]
> Not that one, this one: accountForIdentifier()

It's part of [MSAL](https://github.com/AzureAD/microsoft-authentication-library-for-objc/blob/daaaa67ccecfde0766018654b966be2f2ad6ef7a/MSAL/src/public/MSALPublicClientApplication.h#L204).

**Comment by pa-akiya-ozawa** [comment]
@dmholmes 

> We can append a dot and our tenant ID on that to pass to accountForIdentifier().

How do you get the tenantID?

**Comment by dmholmes** [comment]
> @dmholmes
> 
> > We can append a dot and our tenant ID on that to pass to accountForIdentifier().
> 
> How do you get the tenantID?

In our case it is already coded in our app, it doesn't change.
