### ISSUE TITLE
Broken Links for Android / iOS SDK integration 

### ISSUE THREAD

**Issue by franferns** [microsoftconnect/ms-intune-app-sdk-ios#476]
**Describe the bug:**
Steps to adding MAM SDK integration missing broken links

**To Reproduce**
For IOS 
![Screenshot 2024-09-30 at 7 18 54 PM](https://github.com/user-attachments/assets/ac385084-54fb-4cf5-ac27-5efc9291e05d)
For Android
![Screenshot 2024-09-30 at 7 22 02 PM](https://github.com/user-attachments/assets/496154c4-e309-4e00-93b9-6f18929b7a45)

throws 404 error. 

![image](https://github.com/user-attachments/assets/7d1b588d-5b2f-47e9-870d-12f4a1b43c3c)

**Comment by wangxiaoms** [comment]
Thanks, we will fix those.
iOS: https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-ios-phase1
Android: https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-android-phase1

**Comment by frpaf** [comment]
I somehow missed seeing this in the docs. Below links were what i was looking for

- https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-ios-phase3
- https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-android-phase3

Thanks

**Comment by Erikre** [comment]
Please consider using an FWLink so that links are maintainable in the future. Also, please never include the locale in the URL (such as 'en-us').

**Comment by Erikre** [comment]
@Kyle-Reis - FYI

**Comment by Erikre** [comment]
@msft-cofitz - FYI

**Comment by msft-cofitz** [comment]
@meghandaly FYI

**Comment by wangxiaoms** [comment]
The link for iOS SDK has been fixed. 
The link for Android SDK can be tracked via Android issue 246 https://github.com/microsoftconnect/ms-intune-app-sdk-android/issues/246
