### ISSUE TITLE
App Crashes During Background/Minimize on Intune-Managed Accounts - calling cmarDeviceComplianceEnabled Intune SDK

### ISSUE THREAD

**Issue by KrystofMacek** [microsoftconnect/ms-intune-app-sdk-ios#481]
**Describe the bug:**

Our app crashes when minimized or moved to the background, and the crash logs show that the Microsoft Intune SDK's cmarDeviceComplianceEnabled method is involved. This issue specifically occurs on devices where the user has authenticated using a Microsoft account that is under Intune management or has compliance policies enforced by their company. 
The crash does not occur on devices using standard Microsoft accounts without any Intune management or compliance settings. 

**To Reproduce**

1. Authenticate using a Microsoft account that is under Intune management and has compliance policies enforced by an organization.
2. Minimize or background the app by pressing the home button or switching to another app.
3. The app may crash when transitioning to the background, with the stack trace referencing cmarDeviceComplianceEnabled and com.apple.frontboard.systemappservices.

**Expected behavior:**
App does not crash while minimized.

**Screenshots and logs:**
<details>
<summary>Crash Logs</summary>

com.apple.main-thread
0  libsystem_kernel.dylib         0x16c8 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x4ec8 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x4de0 mach_msg_overwrite + 436
3  libsystem_kernel.dylib         0x4c20 mach_msg + 24
4  CoreFoundation                 0x53f5c __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x53600 __CFRunLoopRun + 1208
6  CoreFoundation                 0x52cd8 CFRunLoopRunSpecific + 608
7  GraphicsServices               0x11a8 GSEventRunModal + 164
8  UIKitCore                      0x40aae8 -[UIApplication _run] + 888
9  UIKitCore                      0x4bed98 UIApplicationMain + 340
10 IntuneMAMSwift                 0x22a3d8 cmarDeviceComplianceEnabled + 2087352
11 mobile                         0x19eb0 main + 7 (AppDelegate.swift:7)
12 ???                            0x1b2dff154 (Missing)

com.microsoft.intune.mam.logging
0  libsystem_kernel.dylib         0x708c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x36e4 _pthread_cond_wait + 1228
2  IntuneMAMSwift                 0x20bcec cmarDeviceComplianceEnabled + 1962700
3  libdispatch.dylib              0x213c _dispatch_call_block_and_release + 32
4  libdispatch.dylib              0x3dd4 _dispatch_client_callout + 20
5  libdispatch.dylib              0xb400 _dispatch_lane_serial_drain + 748
6  libdispatch.dylib              0xbf30 _dispatch_lane_invoke + 380
7  libdispatch.dylib              0x16cb4 _dispatch_root_queue_drain_deferred_wlh + 288
8  libdispatch.dylib              0x16528 _dispatch_workloop_worker_thread + 404
9  libsystem_pthread.dylib        0x4934 _pthread_wqthread + 288
10 libsystem_pthread.dylib        0x10cc start_wqthread + 8

WebThread
0  libsystem_kernel.dylib         0x16c8 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x4ec8 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x4de0 mach_msg_overwrite + 436
3  libsystem_kernel.dylib         0x4c20 mach_msg + 24
4  CoreFoundation                 0x53f5c __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x53600 __CFRunLoopRun + 1208
6  CoreFoundation                 0x52cd8 CFRunLoopRunSpecific + 608
7  WebCore                        0x13927f4 <redacted> + 780
8  libsystem_pthread.dylib        0x606c _pthread_start + 136
9  libsystem_pthread.dylib        0x10d8 thread_start + 8

com.apple.uikit.eventfetch-thread
0  libsystem_kernel.dylib         0x16c8 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x4ec8 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x4de0 mach_msg_overwrite + 436
3  libsystem_kernel.dylib         0x4c20 mach_msg + 24
4  CoreFoundation                 0x53f5c __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x53600 __CFRunLoopRun + 1208
6  CoreFoundation                 0x52cd8 CFRunLoopRunSpecific + 608
7  Foundation                     0xc7b5c -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 212
8  Foundation                     0xc79ac -[NSRunLoop(NSRunLoop) runUntilDate:] + 64
9  UIKitCore                      0x41e81c -[UIEventFetcher threadMain] + 420
10 Foundation                     0xde428 __NSThread__start__ + 732
11 libsystem_pthread.dylib        0x606c _pthread_start + 136
12 libsystem_pthread.dylib        0x10d8 thread_start + 8

io.flutter.1.ui
0  libsystem_kernel.dylib         0x16c8 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x4ec8 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x4de0 mach_msg_overwrite + 436
3  libsystem_kernel.dylib         0x4c20 mach_msg + 24
4  CoreFoundation                 0x53f5c __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x53600 __CFRunLoopRun + 1208
6  CoreFoundation                 0x52cd8 CFRunLoopRunSpecific + 608
7  Flutter                        0x2e941c (Missing UUID 4c4c44a155553144a10bba395f834693)
8  Flutter                        0x2e8a90 (Missing UUID 4c4c44a155553144a10bba395f834693)
9  libsystem_pthread.dylib        0x606c _pthread_start + 136
10 libsystem_pthread.dylib        0x10d8 thread_start + 8

io.flutter.1.raster
0  libsystem_kernel.dylib         0x16c8 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x4ec8 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x4de0 mach_msg_overwrite + 436
3  libsystem_kernel.dylib         0x4c20 mach_msg + 24
4  CoreFoundation                 0x53f5c __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x53600 __CFRunLoopRun + 1208
6  CoreFoundation                 0x52cd8 CFRunLoopRunSpecific + 608
7  Flutter                        0x2e941c (Missing UUID 4c4c44a155553144a10bba395f834693)
8  Flutter                        0x2e8a90 (Missing UUID 4c4c44a155553144a10bba395f834693)
9  libsystem_pthread.dylib        0x606c _pthread_start + 136
10 libsystem_pthread.dylib        0x10d8 thread_start + 8

io.flutter.1.io
0  libsystem_kernel.dylib         0x16c8 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x4ec8 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x4de0 mach_msg_overwrite + 436
3  libsystem_kernel.dylib         0x4c20 mach_msg + 24
4  CoreFoundation                 0x53f5c __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x53600 __CFRunLoopRun + 1208
6  CoreFoundation                 0x52cd8 CFRunLoopRunSpecific + 608
7  Flutter                        0x2e941c (Missing UUID 4c4c44a155553144a10bba395f834693)
8  Flutter                        0x2e8a90 (Missing UUID 4c4c44a155553144a10bba395f834693)
9  libsystem_pthread.dylib        0x606c _pthread_start + 136
10 libsystem_pthread.dylib        0x10d8 thread_start + 8

io.worker.1
0  libsystem_kernel.dylib         0x708c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x36e4 _pthread_cond_wait + 1228
2  Flutter                        0x56f40 (Missing UUID 4c4c44a155553144a10bba395f834693)
3  Flutter                        0x2e26e4 (Missing UUID 4c4c44a155553144a10bba395f834693)
4  libsystem_pthread.dylib        0x606c _pthread_start + 136
5  libsystem_pthread.dylib        0x10d8 thread_start + 8

io.worker.2
0  libsystem_kernel.dylib         0x708c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x36e4 _pthread_cond_wait + 1228
2  Flutter                        0x56f40 (Missing UUID 4c4c44a155553144a10bba395f834693)
3  Flutter                        0x2e26e4 (Missing UUID 4c4c44a155553144a10bba395f834693)
4  libsystem_pthread.dylib        0x606c _pthread_start + 136
5  libsystem_pthread.dylib        0x10d8 thread_start + 8

io.worker.3
0  libsystem_kernel.dylib         0x708c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x36e4 _pthread_cond_wait + 1228
2  Flutter                        0x56f40 (Missing UUID 4c4c44a155553144a10bba395f834693)
3  Flutter                        0x2e26e4 (Missing UUID 4c4c44a155553144a10bba395f834693)
4  libsystem_pthread.dylib        0x606c _pthread_start + 136
5  libsystem_pthread.dylib        0x10d8 thread_start + 8

io.worker.4
0  libsystem_kernel.dylib         0x708c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x36e4 _pthread_cond_wait + 1228
2  Flutter                        0x56f40 (Missing UUID 4c4c44a155553144a10bba395f834693)
3  Flutter                        0x2e26e4 (Missing UUID 4c4c44a155553144a10bba395f834693)
4  libsystem_pthread.dylib        0x606c _pthread_start + 136
5  libsystem_pthread.dylib        0x10d8 thread_start + 8

io.worker.5
0  libsystem_kernel.dylib         0x708c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x36e4 _pthread_cond_wait + 1228
2  Flutter                        0x56f40 (Missing UUID 4c4c44a155553144a10bba395f834693)
3  Flutter                        0x2e26e4 (Missing UUID 4c4c44a155553144a10bba395f834693)
4  libsystem_pthread.dylib        0x606c _pthread_start + 136
5  libsystem_pthread.dylib        0x10d8 thread_start + 8

io.worker.6
0  libsystem_kernel.dylib         0x708c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x36e4 _pthread_cond_wait + 1228
2  Flutter                        0x56f40 (Missing UUID 4c4c44a155553144a10bba395f834693)
3  Flutter                        0x2e26e4 (Missing UUID 4c4c44a155553144a10bba395f834693)
4  libsystem_pthread.dylib        0x606c _pthread_start + 136
5  libsystem_pthread.dylib        0x10d8 thread_start + 8

dart:io EventHandler
0  libsystem_kernel.dylib         0x84c8 kevent + 8
1  Flutter                        0x5a1f0c (Missing UUID 4c4c44a155553144a10bba395f834693)
2  Flutter                        0x5cfa00 (Missing UUID 4c4c44a155553144a10bba395f834693)
3  libsystem_pthread.dylib        0x606c _pthread_start + 136
4  libsystem_pthread.dylib        0x10d8 thread_start + 8

io.worker.1
0  libsystem_kernel.dylib         0x708c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x36e4 _pthread_cond_wait + 1228
2  Flutter                        0x56f40 (Missing UUID 4c4c44a155553144a10bba395f834693)
3  Flutter                        0x2e26e4 (Missing UUID 4c4c44a155553144a10bba395f834693)
4  libsystem_pthread.dylib        0x606c _pthread_start + 136
5  libsystem_pthread.dylib        0x10d8 thread_start + 8

io.worker.2
0  libsystem_kernel.dylib         0x708c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x36e4 _pthread_cond_wait + 1228
2  Flutter                        0x56f40 (Missing UUID 4c4c44a155553144a10bba395f834693)
3  Flutter                        0x2e26e4 (Missing UUID 4c4c44a155553144a10bba395f834693)
4  libsystem_pthread.dylib        0x606c _pthread_start + 136
5  libsystem_pthread.dylib        0x10d8 thread_start + 8

io.worker.3
0  libsystem_kernel.dylib         0x708c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x36e4 _pthread_cond_wait + 1228
2  Flutter                        0x56f40 (Missing UUID 4c4c44a155553144a10bba395f834693)
3  Flutter                        0x2e26e4 (Missing UUID 4c4c44a155553144a10bba395f834693)
4  libsystem_pthread.dylib        0x606c _pthread_start + 136
5  libsystem_pthread.dylib        0x10d8 thread_start + 8

io.worker.4
0  libsystem_kernel.dylib         0x708c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x36e4 _pthread_cond_wait + 1228
2  Flutter                        0x56f40 (Missing UUID 4c4c44a155553144a10bba395f834693)
3  Flutter                        0x2e26e4 (Missing UUID 4c4c44a155553144a10bba395f834693)
4  libsystem_pthread.dylib        0x606c _pthread_start + 136
5  libsystem_pthread.dylib        0x10d8 thread_start + 8

Thread
0  libsystem_pthread.dylib        0x10c4 start_wqthread + 8255066306

Crashed: com.apple.NSURLSession-work
0  libsqlite3.dylib               0x196dc sqlite3_finalize + 16784
1  libsqlite3.dylib               0x17d04 sqlite3_finalize + 10168
2  libsqlite3.dylib               0x17538 sqlite3_finalize + 8172
3  libsqlite3.dylib               0x162d8 sqlite3_finalize + 3468
4  libsqlite3.dylib               0x9e2f0 sqlite3_sourceid + 53824
5  libsqlite3.dylib               0x2d240 sqlite3_step + 6552
6  libsqlite3.dylib               0x2bc6c sqlite3_step + 964
7  CFNetwork                      0x65850 CFHTTPCookieCreateWithResponseHeaderFields + 40908
8  CFNetwork                      0x64230 CFHTTPCookieCreateWithResponseHeaderFields + 35244
9  CFNetwork                      0x63e90 CFHTTPCookieCreateWithResponseHeaderFields + 34316
10 CFNetwork                      0x49a4c _CFURLResponseCreateFromArchiveList + 232884
11 CFNetwork                      0x493fc _CFURLResponseCreateFromArchiveList + 231268
12 CFNetwork                      0x48f28 _CFURLResponseCreateFromArchiveList + 230032
13 CFNetwork                      0xc8948 CFHostCreateWithName + 109404
14 CFNetwork                      0xc3660 CFHostCreateWithName + 88180
15 libdispatch.dylib              0x12e5c _dispatch_block_async_invoke2 + 148
16 libdispatch.dylib              0x3dd4 _dispatch_client_callout + 20
17 libdispatch.dylib              0xb400 _dispatch_lane_serial_drain + 748
18 libdispatch.dylib              0xbf64 _dispatch_lane_invoke + 432
19 libdispatch.dylib              0x16cb4 _dispatch_root_queue_drain_deferred_wlh + 288
20 libdispatch.dylib              0x16528 _dispatch_workloop_worker_thread + 404
21 libsystem_pthread.dylib        0x4934 _pthread_wqthread + 288
22 libsystem_pthread.dylib        0x10cc start_wqthread + 8

com.google.firebase.crashlytics.MachExceptionServer
0  FirebaseCrashlytics            0x1d3b8 FIRCLSProcessRecordAllThreads + 393 (FIRCLSProcess.c:393)
1  FirebaseCrashlytics            0x1d798 FIRCLSProcessRecordAllThreads + 424 (FIRCLSProcess.c:424)
2  FirebaseCrashlytics            0x14944 FIRCLSHandler + 34 (FIRCLSHandler.m:34)
3  FirebaseCrashlytics            0x171c8 FIRCLSMachExceptionServer + 521 (FIRCLSMachException.c:521)
4  libsystem_pthread.dylib        0x606c _pthread_start + 136
5  libsystem_pthread.dylib        0x10d8 thread_start + 8

com.apple.NSURLConnectionLoader
0  libsystem_kernel.dylib         0x16c8 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x4ec8 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x4de0 mach_msg_overwrite + 436
3  libsystem_kernel.dylib         0x4c20 mach_msg + 24
4  CoreFoundation                 0x53f5c __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x53600 __CFRunLoopRun + 1208
6  CoreFoundation                 0x52cd8 CFRunLoopRunSpecific + 608
7  CFNetwork                      0xfdc7c _CFHostIsDomainTopLevel + 108176
8  Foundation                     0xde428 __NSThread__start__ + 732
9  libsystem_pthread.dylib        0x606c _pthread_start + 136
10 libsystem_pthread.dylib        0x10d8 thread_start + 8

Thread
0  libsystem_kernel.dylib         0x1450 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x4980 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0x10cc start_wqthread + 8

Thread
0  libsystem_pthread.dylib        0x10c4 start_wqthread + 8255066306

Thread
0  libsystem_pthread.dylib        0x10c4 start_wqthread + 8255066306

Thread
0  libsystem_kernel.dylib         0x165c semaphore_timedwait_trap + 8
1  libdispatch.dylib              0x43ec _dispatch_sema4_timedwait + 64
2  libdispatch.dylib              0x49e8 _dispatch_semaphore_wait_slow + 76
3  IntuneMAMSwift                 0x3625c cmarDeviceComplianceEnabled + 38972
4  IntuneMAMSwift                 0x14eb3c cmarDeviceComplianceEnabled + 1188124
5  libdispatch.dylib              0x213c _dispatch_call_block_and_release + 32
6  libdispatch.dylib              0x3dd4 _dispatch_client_callout + 20
7  libdispatch.dylib              0xb400 _dispatch_lane_serial_drain + 748
8  libdispatch.dylib              0xbf30 _dispatch_lane_invoke + 380
9  libdispatch.dylib              0x16cb4 _dispatch_root_queue_drain_deferred_wlh + 288
10 libdispatch.dylib              0x16528 _dispatch_workloop_worker_thread + 404
11 libsystem_pthread.dylib        0x4934 _pthread_wqthread + 288
12 libsystem_pthread.dylib        0x10cc start_wqthread + 8
</details>

**Smartphone (please complete the following information):**
 - Device: iPhone 12, 15, 14
 - OS: iOS 17.5.1, iOS 18.0.1

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version?
Currently using latest 20.1.2 version. But happens also in app versions that have earlier version.

- What platform is your app based in (native, Xamarin based, Cordova, etc)?
Native iOS

- For errors during build, does the app build without Intune SDK integration?
No errors during build

- For errors post build, does the app launch without being Intune SDK integrated?
Yes only with Intune SDK Integrated, and only for accounts with Intune management or compliance 

- Do you see a trend with it only being reproduced on a specific device?
No

**Comment by wangxiaoms** [comment]
Hi when Background/Minimize app on Intune managed accounts, how often is app crashed, most of the time or only randomly? Does your app have Intune diagnostic console enabled to get MAM logs?
https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-ios-appendix#how-can-i-troubleshoot-my-app

**Comment by KrystofMacek** [comment]
Hi @wangxiaoms, the crash doesn't occur for all users but does happen consistently for a subset of them. For these affected users, it crashes nearly every time the app is minimized or sent to the background. I haven't been able to gather additional logs beyond what I've previously shared from Crashlytics. Our app does not have the Intune diagnostic console.

**Comment by wangxiaoms** [comment]
Hi as team checked we will need more information, would you enable Intune diagnostic console, then get below:
- Repo video 
- MAM logs
- Crash logs 
- MAM policy details
- Is the app accessing any data in the background

**Comment by KrystofMacek** [comment]
Hi @wangxiaoms, I will look into adding diagnostic console - is it possible to collect logs from diagnostic console outside of development environment? As I mentioned this issue only appears for clients using intune management but for us locally we were not able to replicate it (yet). And its currently only happening in production versions of the app. Thats why the crash logs i provided are from Crashlytics - the only crash stacktrice we were able to get is the one i shared in initial post.

The repo video if you mean video of the crash happening, i have only screenshot of the generic "app stopped working" system dialog - this dialog pops up after a while if the app is in background. As of now, we were not able detect any specific action within the app that would cause this:
![image](https://github.com/user-attachments/assets/834b2f3c-5c71-40cf-a3f8-c44f00fafc44)

Policy details: Client uses policies to enforce MFA and Conditional access, also disable copying content from app. 
App is not accessing any data in background, everything is paused when minimizing the app.

Please let me know if you need more info, and also about the diagnostic console - if its something you cant move forward without. 

Thanks

**Comment by wangxiaoms** [comment]
Hi the Intune Dianostic Console will need to be enabled via minor code change, then release the app new version to production for users to open the console and share logs.
https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-ios-appendix#how-can-i-troubleshoot-my-app

There is another way to get logs from device backup.
1. Install iTunes using standalone installer. (iExplorer doesn’t support Microsoft Store version of iTunes)
2. Backup your iOS with iTunes (Or Finder on macOS)
3. Launch ‘ iExplorer ’ app and browse the iOS backup
4. MAM logs are located in following directories. You can extract the files to PC/Mac.
    - Backup Explorer App --<app.bundle.id> IntuneMAM
    - Backup Explorer App Group --<app.group.id> IntuneMAM --<app.bundle.
 
<img width="901" alt="image" src="https://github.com/user-attachments/assets/775bf736-b498-41ab-95e7-106bd7ae661c">

**Comment by KrystofMacek** [comment]
Hi @wangxiaoms, sending the Intune Dianostic Console logs file exported after crash occured.

info.plist:

`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CADisableMinimumFrameDurationOnPhone</key>
	<true/>
	<key>CFBundleDevelopmentRegion</key>
	<string>$(DEVELOPMENT_LANGUAGE)</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>com.example.app</string> 
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>${PRODUCT_NAME}</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>$(FLUTTER_BUILD_NAME)</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleURLName</key>
			<string>com.example.app</string> 
			<key>CFBundleURLSchemes</key>
			<array>
				<string>db-placeholder1</string> 
				<string>db-placeholder2-intunemam</string> 
				<string>ShareMedia-com.example.app</string> 
				<string>ShareMedia-com.example.app-intunemam</string> 
				<string>msauth.com.microsoft.intunemam</string>
				<string>eu.example.app</string> 
			</array>
		</dict>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>msauth.com.example.app</string> 
				<string>msauth.com.example.app-intunemam</string> 
				<string>com.googleusercontent.apps.placeholder</string> 
				<string>com.googleusercontent.apps.placeholder-intunemam</string> 
				<string>com.googleusercontent.apps.placeholder2</string> 
				<string>com.googleusercontent.apps.placeholder2-intunemam</string> 
				<string>com.googleusercontent.apps.placeholder3</string> 
				<string>com.googleusercontent.apps.placeholder3-intunemam</string> 
			</array>
		</dict>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLName</key>
			<string></string>
			<key>CFBundleURLSchemes</key>
			<array/>
		</dict>
	</array>
	<key>CFBundleVersion</key>
	<string>$(FLUTTER_BUILD_NUMBER)</string>
	<key>FirebaseAutomaticScreenReportingEnabled</key>
	<false/>
	<key>FlutterDeepLinkingEnabled</key>
	<true/>
	<key>ITSAppUsesNonExemptEncryption</key>
	<false/>
	<key>IntuneMAMSettings</key>
	<dict>
		<key>ADALAuthority</key>
		<string>https://login.microsoftonline.com/common</string>
		<key>ADALClientId</key>
		<string>placeholder-client-id</string> 
		<key>ADALRedirectUri</key>
		<string>msauth.com.example.app://auth</string> 
		<key>AppGroupIdentifiers</key>
		<array>
			<string>group.com.example.app</string> 
		</array>
		<key>DebugSettingsEnabled</key>
		<false/>
	</dict>
	<key>LSApplicationQueriesSchemes</key>
	<array>
		<string>scmx</string>
		<string>skycure</string>
		<string>lookoutwork-ase</string>
		<string>companyportal</string>
		<string>mvisionmobile</string>
		<string>ms-excel</string>
		<string>ms-excel-intunemam</string>
		<string>wandera</string>
		<string>smart-ns</string>
		<string>smsec</string>
		<string>betteractiveshield</string>
		<string>microsoft-edge-https</string>
		<string>microsoft-edge-https-intunemam</string>
		<string>dbapi-placeholder</string> 
		<string>dbapi-placeholder-intunemam</string> 
		<string>msauthv3</string>
		<string>ms-word</string>
		<string>ms-word-intunemam</string>
		<string>ms-powerpoint</string>
		<string>ms-powerpoint-intunemam</string>
		<string>ms-office</string>
		<string>ms-office-intunemam</string>
		<string>ms-outlook</string>
		<string>ms-outlook-intunemam</string>
		<string>lacoonsecurity</string>
		<string>microsoft-edge-http</string>
		<string>microsoft-edge-http-intunemam</string>
		<string>ms-onedrive</string>
		<string>ms-onedrive-intunemam</string>
		<string>zips</string>
		<string>dbapi-placeholder-emm</string> 
		<string>dbapi-placeholder-emm-intunemam</string> 
		<string>msauthv2</string>
		<string>https-intunemam</string>
		<string>http-intunemam</string>
	</array>
	<key>LSHasLocalizedDisplayName</key>
	<true/>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>NFCReaderUsageDescription</key>
	<string>To scan for NFC tags</string>
	<key>NSAppleMusicUsageDescription</key>
	<string>This permission is not needed by the app, but it is required by an underlying API. If you see this dialog, contact us.</string>
	<key>NSBluetoothAlwaysUsageDescription</key>
	<string>To scan for nearby printers with iBeacon</string>
	<key>NSBluetoothPeripheralUsageDescription</key>
	<string>To check Bluetooth status for scanning nearby printers</string>
	<key>NSBonjourServices</key>
	<array>
		<string>_dartobservatory._tcp</string>
	</array>
	<key>NSCameraUsageDescription</key>
	<string>Access to camera is required for scanning QR codes</string>
	<key>NSFaceIDUsageDescription</key>
	<string>To make app more secure</string>
	<key>NSFileProviderDomainUsageDescription</key>
	<string>Files permission is required for accessing files to print</string>
	<key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
	<string>To scan for nearby printers with iBeacon</string>
	<key>NSLocationAlwaysUsageDescription</key>
	<string>To scan for nearby printers with iBeacon</string>
	<key>NSLocationWhenInUseUsageDescription</key>
	<string>To scan for nearby printers with iBeacon</string>
	<key>NSPhotoLibraryAddUsageDescription</key>
	<string>Access to library is required for uploading files</string>
	<key>NSPhotoLibraryUsageDescription</key>
	<string>To upload photos for profile or print</string>
	<key>NSUbiquitousContainers</key>
	<dict>
		<key>iCloud.com.example.app</key> 
		<dict>
			<key>NSUbiquitousContainerIsDocumentScopePublic</key>
			<true/>
			<key>NSUbiquitousContainerName</key>
			<string>${PRODUCT_NAME}</string>
			<key>NSUbiquitousContainerSupportedFolderLevels</key>
			<string>Any</string>
		</dict>
	</dict>
	<key>UIApplicationSupportsIndirectInputEvents</key>
	<true/>
	<key>UIFileSharingEnabled</key>
	<true/>
	<key>UILaunchStoryboardName</key>
	<string>$(USER_LAUNCH_SCREEN)</string>
	<key>UIMainStoryboardFile</key>
	<string>Main</string>
	<key>UIRequiresFullScreen</key>
	<true/>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UISupportsDocumentBrowser</key>
	<true/>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
	<key>aps-environment</key>
	<string>development</string>
	<key>com.apple.developer.nfc.readersession.felica.systemcodes</key>
	<array>
		<string>XXXX</string> 
	</array>
	<key>com.apple.developer.nfc.readersession.formats</key>
	<array>
		<string>TAG</string>
		<string>NDEF</string>
	</array>
	<key>com.apple.developer.nfc.readersession.iso7816.select-identifiers</key>
	<array>
		<string>XXXXXX</string> 
	</array>
</dict>
</plist>
`

[IntuneMAMDiagnosticFiles.txt](https://github.com/user-attachments/files/17713857/IntuneMAMDiagnosticFiles.txt)

**Comment by wangxiaoms** [comment]
Hi @KrystofMacek the team has checked this case and suggested below:
Set MaxFileProtectionLevel within the IntuneMAMSettings dictionary in the Info.plist file to NSFileProtectionCompleteUntilFirstUserAuthentication . You will find more details here: 
https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-ios-phase3#configure-settings-for-the-intune-app-sdk

With below stack it does seem the app is trying to access files in the background.
Crashed: com.apple.NSURLSession-work
0 libsqlite3.dylib 0x196dc sqlite3_finalize + 16784
1 libsqlite3.dylib 0x17d04 sqlite3_finalize + 10168
2 libsqlite3.dylib 0x17538 sqlite3_finalize + 8172
3 libsqlite3.dylib 0x162d8 sqlite3_finalize + 3468
4 libsqlite3.dylib 0x9e2f0 sqlite3_sourceid + 53824
5 libsqlite3.dylib 0x2d240 sqlite3_step + 6552
6 libsqlite3.dylib 0x2bc6c sqlite3_step + 964

**Comment by KrystofMacek** [comment]
@wangxiaoms Hi, it seems that setting NSFileProtectionCompleteUntilFirstUserAuthentication solved the crash. Will keep monitoring but for now I would say that was the issue. Thanks for help
