### ISSUE TITLE
Intune App Protection Policy blocks URL opening in MS Edge when using .universalLinksOnly option

### ISSUE THREAD

**Issue by rahulVermaSimpplr** [microsoftconnect/ms-intune-app-sdk-ios#486]
**Describe the bug:**
When using the Intune SDK with enforced App Protection Policies, attempting to open URLs in MS Edge via the demo application (as well as in my own app) results in an "Action not allowed" popup if the `.universalLinksOnly: true` option is specified in the URL open request. This issue appears to be related to Intune SDK handling of App Protection Policies, as the same behavior is seen in both the demo app and my protected app.

**To Reproduce**
1. Download and install the Intune SDK demo application [here](https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://github.com/microsoftconnect/Chatr-Sample-Intune-iOS-App&ved=2ahUKEwim_YnU2cmJAxX7S2wGHSoCJ9cQFnoECBYQAQ&usg=AOvVaw3My_sdcx_sLuDa5f0QuetW).
2. Apply an App Protection Policy that restricts data transfer to only policy-managed apps.
3. Login into the app and 
4. Attempt to open a URL using `UIApplication.shared.open(reqURL, options: [.universalLinksOnly: true])`.
5. Observe that the app shows an "Action not allowed" popup and the URL does not open in MS Edge, despite Edge being policy-managed.

**Expected behavior:**
The URL should open in MS Edge if it is a policy-managed app, even when the `.universalLinksOnly: true` option is specified.

**Screenshots and logs:**
- 
![Screenshot 2024-11-07 at 12 46 38 PM](https://github.com/user-attachments/assets/6ef5e450-4944-42e0-a3ed-e30068c1f5f1)

- No crash logs, but error messages related to "Action not allowed" can be observed - 
`Action Not Allowed

Your organization only allows you to transfer its data to other managed`

**Smartphone (please complete the following information):**
 - Device: iPhone 14
 - OS: iOS 18 (also encountered on iOS 17 and other devices)

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version? - Yes, using version 19.7.1
- What platform is your app based in? - Native
- Who is the customer? - Multiple customers are facing this issue
- Do you see a trend with it only being reproduced on a specific device? - No, it is reproducible on any iOS device

**Additional context:**
This issue was initially observed in my own Intune SDK-protected app, prompting me to test it with the Intune SDK demo application to verify whether the problem was specific to my app. Since the same behavior occurs in the demo app, this confirms it is an Intune SDK-related issue.

**Comment by wangxiaoms** [comment]
Hi, can you share the code changes you made to the Chatr sample app, I will try to test it.

**Comment by rahulVermaSimpplr** [comment]
Hi @wangxiaoms, just add `UIApplication.shared.open(reqURL, options: [.universalLinksOnly: true])` anywhere in the chattr app after login (any button press or tableView's `didSelectRow`) to open URL with any dummy URL like `hitps://www.google.com` and you would be able to reproduce this issues, if any further help needed do let me know.

**Comment by wangxiaoms** [comment]
Hi, for universalLinksOnly, URLs must be universal links and have an app configured to open them. You can test it within an app that does Not have Intune SDK integrated, to make sure the universal link is working. After that you can test with Intune SDK, and follow below: https://learn.microsoft.com/en-us/mem/intune/apps/app-protection-policy-settings-ios#universal-links

**Comment by rahulVermaSimpplr** [comment]
@wangxiaoms that's the question if the link is universal link and app isn't installed in user's device it should just fail to open that link, but it's giving popup in that case which it shouldn't as in fallback case we are handling this separately but the alert shown by Intune SDK confuses the user.

**Comment by wangxiaoms** [comment]
Hi as you mentioned "_Expected behavior: The URL should open in MS Edge if it is a policy-managed app, even when the .universalLinksOnly: true option is specified._". Even in an app without Intune SDK, the dummy universal link will not open in browser.

**Comment by wangxiaoms** [comment]
For dummy universal link the error prompt is expected, for valid universal link an application associated with the link instead of a protected browser is launched. https://learn.microsoft.com/en-us/mem/intune/apps/app-protection-policy-settings-ios#universal-links
