### ISSUE TITLE
v20.x breaking API change vs v19.x

### ISSUE THREAD

**Issue by andrejacobs-unily** [microsoftconnect/ms-intune-app-sdk-ios#489]
I am in the process of upgrading our codebase to Xcode 16 and using the latest Intune MAM SDK v20.x

Discovered that the code doesn't compile because we implemented the `IntuneMAMComplianceDelegate`. Which is v19 and prior required this method `func identity(_ identity: String, hasComplianceStatus status: IntuneMAMComplianceStatus, withErrorMessage errMsg: String, andErrorTitle errTitle: String)`.

The closest match I can find for v20 is `func accountId(_ accountId: String, hasComplianceStatus status: IntuneMAMComplianceStatus, withErrorMessage errMsg: String, andErrorTitle errTitle: String)` and appears only the method name was changed.

The documentation only covers this new method name https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-ios-phase6.

Can you please document breaking API changes?
Perhaps even have a specific document that has migration steps to go from vX to vY would be amazing.
At the moment I can only guess and hope that only the method name was changed and that behaviour etc. is all still the same.

Thank you.

**Comment by wangxiaoms** [comment]
Hi the document is here (https://github.com/microsoftconnect/ms-intune-app-sdk-ios/discussions/460), you can in addition refer to the header file IntuneMAMComplianceManager.h

**Comment by andrejacobs-unily** [comment]
Thank you.
