### ISSUE TITLE
Differences in Intune SDK, Android SDK vs IOS SDK, Compile time knowledge of MSAL clientid

### ISSUE THREAD

**Issue by dickverweij** [microsoftconnect/ms-intune-app-sdk-ios#490]
**Describe the bug:**
Our app is a multiplatform hybrid app which targets both IOS an Android with the same code base.
Our app is currently deployed to millions of app users. Our customers are employers, their employees as app users.
A portion of the customers (employers) want to impose Microsoft Intune MAM policies on our app

During the implementation of our app with Intune Android SDK we found that we could build the android version **without** configuring a MSAL clientid. At compile time we do not know a MSAL clientid, the apps runs fine. It takes the UPN and policy of the company portal app for the configured android app. All this without login in MSAL in our app. The enrollment is automatic.

**The IOS version does not work because it needs a MSAL clientid. But we do not know this value at compile time**

In Android we could monitor the following properties during startup
MAMComponents.isCompanyPortalInstalled(getApplicationContext());
MAMComponents.isManagedApp(getApplicationContext());

Question: what are the IOS equivalents of those functions?

**Comment by dickverweij** [comment]
Correction; We could build and run a IOS version without specifing the client id. We just had to include the msal framework for that.

Questions remain: 
Is there a way to check if the company portal app is installed on the (IOS) device?

**Comment by kanishkaBagga** [comment]
@dickverweij - When implementing Microsoft Intune MAM policies in an iOS app, you don't have direct equivalents to the Android methods MAMComponents.isCompanyPortalInstalled or MAMComponents.isManagedApp. Microsoft Intune MAM for iOS operates differently, and the SDK itself doesn't provide an API to explicitly check for the presence of the Company Portal app or if the app is being managed by Intune. 


Here are some approaches and best practices:

1) Managed App Detection:Intune MAM on iOS uses the app configuration and app protection policies pushed from the Intune admin center. If your app is being managed, you can determine this through the MAM SDK's identity-related APIs.
The IntuneMAMPolicy class provides APIs to check if your app is managed:

BOOL isAppManaged = [[IntuneMAMPolicy instance] isAppManaged];

This method can be called to determine if your app is managed by Intune, which may indicate that the Company Portal app is installed and the app is under Intune management.

iOS apps are sandboxed, so there is no direct API to detect the presence of other apps (like the Company Portal) on the device. Instead, you rely on the MAM SDK to indicate whether your app is managed and policies are applied.
Apple’s App Store guidelines prohibit directly querying the installed apps on a device for privacy reasons.

**Comment by dickverweij** [comment]
Thanks @kanishkaBagga  I've managed to detect the company portal app like this:

[[UIApplication sharedApplication] canOpenURL:[NSURL URLWithString: @"companyportal://apps/nl.afas.pocket2"]]

**Comment by kanishkaBagga** [comment]
Hi @dickverweij , are we good to close?

**Comment by kanishkaBagga** [comment]
Closing as this is completed
