### ISSUE TITLE
Issue implementing the Intune SDK : app can't open files

### ISSUE THREAD

**Issue by AntoineRuf-px** [microsoftconnect/ms-intune-app-sdk-ios#492]
We implemented the Intune SDK for iOS into our application, which allows the user to open files with a certain file extension. These file extensions are correctly contained within the various sections of the Info.plist (CFBundleDocumentTypes and UTExportedTypeDeclarations.) The non-Intune version of the app opens files without an issue. The Intune version doesn't even seem to receive the URL request, according to our testing.

A user is enrolled with the company portal, and app protection policies are enabled (the only one we enabled is the PIN).
Enclosed you'll find the IntuneMAMDiagnostic dialog (anonymized). It seems there are URLs requests for the file here, but it seems to me that the Intune SDK prevents the app from receiving those requests.

Could you help me understand what is going on ? We'd like for our users to be able to use Intune with our product.

Device tested is an iPhone 14, iOS 18.1
SDK version is 20.1.2.
[IntuneMAMDiagnosticFiles.txt](https://github.com/user-attachments/files/17777376/IntuneMAMDiagnosticFiles.txt)

Best regards,

Antoine Ruffion.

**Comment by jitheshncxe** [comment]
Thanks @AntoineRuf-px for reporting...Let me please go through the log and update you...

**Comment by jitheshncxe** [comment]
@AntoineRuf-px  could you please list the file name/extensions which are blocked after integrating the application with MAM SDK?

**Comment by AntoineRuf-px** [comment]
Hello @jitheshncxe ,
The app doesn't seem to be able to open any files after integrating. Most of the files concerned here have proprietary extensions. The two extensions used inthe logs I have provided are ".zed" and ".zaf".

**Comment by jitheshncxe** [comment]
Hi @AntoineRuf-px, checking the MAM logs I see the policies are applied successfully. I am not sure if one of the policies is causing the issue you are seeing, specifically the one OpenDataFromManagedLocations = 23 which indicates data can be accessed only from Photo Library, OneDrive, SharePoint & Camera, whereas the file path I could find in the log is like file:///private/var/mobile/Containers/Data/Application/0936B2A6-2FA8-40B5-B98B-0D1E13C1B54A/tmp/.IntuneMAM/C666C4A9-6B73-423C-9206-FB2665940633/Alice.zaf. So, could you please share some more details I listed below?

1. Screen recording of the file open procedure (If this is initiated from UI of your application).
2. What is the file location.
3. The app code to open files.
4. The error received from app file open method.

**Comment by AntoineRuf-px** [comment]
Hello @jitheshncxe ,

I have been able to control whether this policy causes the issue, but I don't think it does : from my understanding, the "OpenDataFromManagedLocations" app policy is superseded by the "Receive Data from Other Apps" app policy, which I set to "all apps". Am I wrong in assuming so ?
Looking at this article : https://learn.microsoft.com/en-us/mem/intune/apps/app-protection-policy-settings-log , it also seems that a setting to add "Local Storage" to the list of acceptable locations to read from exists. However, I don't seem to be able to activate this feature into my Intune console. Is there an issue there, or is that a deprecated parameter ?

I would also like to add that even without App Protection Policies active, the behaviour is the same : the app just doesn't seem to receive any request to open a file.

Sadly, due to security constraints, I cannot share code or video relative to the opening of the files. Here are the answers to your questions, to the best of my ability :

- The open file procedure is currently done out of application : we are using the "Share file..." action in the Quicklook to send it to the app.
- The file we are trying to open is indeed not at the path currently trying to be opened by the application : does the Intune SDK do anything with the file paths of work data ? Should we direct our application towards specific folders in which to open files ?
- I am sadly not at liberty to share how we open files in our application, due to security reasons. However, I can tell you that on request, we usually copy the file requesting an open to a folder contained in the app container. Verifying the contents of the container, there doesn't seem to be any file on our end.
- Our method to open files is never called : the app doesn't even seem to see there's a file open request. Therefore, it seems to me that the Intune SDK intercepts and filters out this request for one reason or another.

**Comment by AntoineRuf-px** [comment]
Hello,

I would like to bump this issue. We're still researching whether the file location affects how the SDK impacts the opening of the files. Help would be greatly appreciated, as this issue is critical for several deployments.

**Comment by jitheshncxe** [comment]
Hi @AntoineRuf-px, thanks for reaching out...I had been researching too see if there is any possibility of SDK intercept file open call made from outside ...Please allow me some more time to get back on this.

**Comment by jitheshncxe** [comment]
Hi @AntoineRuf-px , you could check the article https://learn.microsoft.com/mem/intune/developer/app-sdk-ios-phase4#copy-to-actions and see if that helps. Also, regarding the external application that you were referring which would invoke the open file procedure, is that something you developed in-house using the QuickLook framework (https://developer.apple.com/documentation/quicklook) and is Intune manged as well?  At any rate, in order for us to debug this further, we would need a local repro. Would you be able to help set up one? I understand you have security concerns to share the application details but if it is fine to share the details with a Microsoft account, we can provide one and communicate accordingly. Please let me know if you like to take that route...Thanks!

**Comment by AntoineRuf-px** [comment]
Thank you for the resources, I'll try to study whether this applies to our case.
Since I can't share the code itself, we'll try to create a new app that works similarly to our code, and send this project to you instead if we manage to reproduce the issue on this new app. I'll keep you posted when I'll be able to send the project.

Regards.

**Comment by jitheshncxe** [comment]
Thanks @AntoineRuf-px. Please reach out once you have a repro to share so that we can help debug it. Until then resolving this query
