### ISSUE TITLE
Test flight build crash after device is locked for 20-30 minutes and Showing crash popup

### ISSUE THREAD

**Issue by work-sunilsaini** [microsoftconnect/ms-intune-app-sdk-ios#503]
**Describe the bug:**
When the app integrated with Intune SDK is locked on an iOS device for around 20-30 minutes and then reopened, the app shows a black screen or Intune lock screen and crashes. A popup appears stating, "[App Name] crashed. Do you want to share additional information with the developer?" This issue occurs despite the app functioning correctly in the foreground or action mode. Facing Test Flight build.

**To Reproduce**
1. Install a fresh build of the app integrated with Intune SDK.
2. Login using an Intune-managed account with policies enabled (e.g., block copy-paste, share app data, enforce PIN, etc.).
3. Lock the iOS device and leave it in the foreground for around 20-30 minutes.
4. Unlock the device and Wait for 3 seconds to see the crash popup.

**Expected behavior:**
The app should resume from the locked state without showing a black screen or crashing. The Intune policies should remain enforced as expected.

**Screenshots and logs:**
Thread 4 Crashed:
0   dyld                          	0x00000001b4cba1a8 void dyld3::MultiMapBase<prebuilt_objc::ObjCStringKeyOnDisk, prebuilt_objc::ObjCObjectOnDiskLocation, prebuilt_objc::HashObjCStringKeyOnDisk, prebuilt_objc::EqualObjCStringKeyOnDisk>::forEachEntry<... + 140 (Map.h:612)
1   dyld                          	0x00000001b4cb5c04 prebuilt_objc::forEachClass(dyld4::RuntimeState*, dyld3::MultiMapView<prebuilt_objc::ObjCStringKeyOnDisk, prebuilt_objc::ObjCObjectOnDiskLocation, prebuilt_objc::HashObjCStringKeyOnDisk, prebuilt_o... + 120 (PrebuiltObjC.cpp:79)
2   dyld                          	0x00000001b4c65e54 dyld4::APIs::_dyld_for_each_objc_class(char const*, void (void*, bool, bool*) block_pointer) + 200 (DyldAPIs.cpp:2502)
3   libobjc.A.dylib               	0x000000018c5b081c getPreoptimizedClass + 132 (objc-opt.mm:361)
4   libobjc.A.dylib               	0x000000018c5b044c getClassExceptSomeSwift(char const*) + 40 (objc-runtime-new.mm:2125)
5   libobjc.A.dylib               	0x000000018c5b02a8 look_up_class + 92 (objc-runtime-new.mm:8563)
6   Foundation                    	0x000000018de9abd8 NSClassFromString + 152 (NSObjCRuntime.m:140)
7   BoardServices                 	0x00000001a8956800 +[BSXPCServiceConnectionProxy invokeMethod:onTarget:withMessage:forConnection:completion:] + 100 (BSXPCServiceConnectionProxy.m:171)
8   BoardServices                 	0x00000001a8939e38 __63-[BSXPCServiceConnectionEventHandler connection:handleMessage:]_block_invoke + 1156 (BSXPCServiceConnectionEventHandler.m:349)
9   BoardServices                 	0x00000001a8938f64 BSXPCServiceConnectionExecuteCallOut + 240 (BSXPCServiceConnection.m:1307)
10  BoardServices                 	0x00000001a8937d2c -[BSXPCServiceConnectionEventHandler connection:handleMessage:] + 176 (BSXPCServiceConnectionEventHandler.m:313)
11  BoardServices                 	0x00000001a893887c -[BSXPCServiceConnection _connection_handleMessage:fromPeer:withHandoff:] + 524 (BSXPCServiceConnection.m:1099)
12  libdispatch.dylib             	0x0000000196fa8370 _dispatch_call_block_and_release + 32 (init.c:1549)
13  libdispatch.dylib             	0x0000000196faa0d0 _dispatch_client_callout + 20 (object.m:576)
14  libdispatch.dylib             	0x0000000196fb16d8 _dispatch_lane_serial_drain + 744 (queue.c:3934)
15  libdispatch.dylib             	0x0000000196fb2214 _dispatch_lane_invoke + 432 (queue.c:4025)
16  libdispatch.dylib             	0x0000000196fb1560 _dispatch_lane_serial_drain + 368 (queue.c:3934)
17  libdispatch.dylib             	0x0000000196fb2214 _dispatch_lane_invoke + 432 (queue.c:4025)
18  libdispatch.dylib             	0x0000000196fbd258 _dispatch_root_queue_drain_deferred_wlh + 288 (queue.c:7193)
19  libdispatch.dylib             	0x0000000196fbcaa4 _dispatch_workloop_worker_thread + 540 (queue.c:6787)
20  libsystem_pthread.dylib       	0x00000002177d3c7c _pthread_wqthread + 288 (pthread.c:2696)
21  libsystem_pthread.dylib       	0x00000002177d0488 start_wqthread + 8

<img width="312" alt="Screenshot 2024-12-09 at 3 14 23 PM" src="https://github.com/user-attachments/assets/c1264155-4eff-4a1f-9549-d325a59279ca">

[logs.txt](https://github.com/user-attachments/files/18058046/logs.txt)

**Smartphone:**
 - Device: iPhone 14
 - OS: 18.1.1

**Intune App SDK for iOS :**
-Intune SDK Version: 20.1.2
-Platform: Flutter(version - 3.24.5) - using FlutterMethodChannel for Intune integration
-The app builds and runs without the Intune SDK integrated.
-With the Intune SDK integrated, the app experiences a crash post-build after resuming from a locked state.

- This crash coming in my all iOS devices. 

**Additional context:**
- The issue occurs consistently after the app is left in a locked state for 20-30 minutes.
- Removing the Intune SDK resolves the crash, but the Intune functionality is required for the app.
- This is a TestFlight build, and the crash logs were retrieved from TestFlight reports.

**Comment by wangxiaoms** [comment]
Hi, can you test it with latest Intune SDK release 20.2.1, also does the app access files at background? if yes then will need to set MaxFileProtectionLevel within the IntuneMAMSettings dictionary to NSFileProtectionCompleteUntilFirstUserAuthentication. https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-ios-phase3#configure-settings-for-the-intune-app-sdk

**Comment by work-sunilsaini** [comment]
After adding this, the crash was resolved.
<key>IntuneMAMSettings</key>
<dict>
     <key>MaxFileProtectionLevel</key>
     <string>NSFileProtectionCompleteUntilFirstUserAuthentication</string>
</dict>
Thanks @wangxiaoms
