### ISSUE TITLE
"Action Not Allowed" Opening Edge (or Outlook)

### ISSUE THREAD

**Issue by dmholmes** [microsoftconnect/ms-intune-app-sdk-ios#507]
We are using the "microsoft-edge-http" scheme to open Edge but receive this error. Can we address this in the app or does it require a policy change?

![ActionNotAllowed2](https://github.com/user-attachments/assets/74b3c541-ba92-4047-9b8b-815109f4d937)

**Comment by wangxiaoms** [comment]
The app and Edge need to be policy-managed, check below links for more information.
- App side, search for edge.
  https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-ios-phase3
- Policy side, search for Edge, if it is Universal link also search for "Universal Links"
  https://learn.microsoft.com/en-us/mem/intune/apps/app-protection-policy-settings-ios

**Comment by dmholmes** [comment]
We have microsoft-edge-http, microsoft-edge-https, microsoft-edge-http-intunemam, and microsoft-edge-https-intunemam in the app Info.plist. I'm the developer and don't have access to the policy settings but I don't see any settings for app prefixes (LSApplicationQueriesSchemes) only Universal Links. The apps we are trying to open don't have Universal Links.

**Comment by wangxiaoms** [comment]
The policy setting is "Restrict web content transfer with other apps" which specify how web content (http/https links) is opened from policy-managed applications. From the error message "_account is not currently managed by Microsoft Intune in the app_", it seems the enrollment may not be successful. Please make sure app and Edge are correctly policy-managed.
