### ISSUE TITLE
[iPad16.3] app list page is empty when share text (meeting link) via Using other apps

### ISSUE THREAD

**Issue by edgar-yang** [microsoftconnect/ms-intune-app-sdk-ios#508]
**Describe the bug:**
[iPad16.3] app list page is empty when sharing text (meeting link) via Using other apps

**To Reproduce**
Using the iPad 16.3, and trying to share the text (meeting link), the share sheet will be empty

**Expected behavior:**
The share sheet should show other apps normally

**Screenshots and logs:**
![image](https://github.com/user-attachments/assets/0d4b828d-20d6-40d5-8dea-d6c8cf4f48d7)

**Smartphone (please complete the following information):**
 - Device: iPad mini (5th generation)
 - OS: 16.3

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? **19.7.0**
- What platform is your app based in (native, Xamarin based, Cordova, etc)? **Native**
- For errors post build, does the app launch without being Intune SDK integrated? **The app works well without integrate the SDK**

**Additional context:**
We tried in different os versions and devices, but it will only reproduce in iPad 16.3.

![image](https://github.com/user-attachments/assets/f3e9aa0f-0de1-4ac1-a578-6e69fca6245a)

**Comment by wangxiaoms** [comment]
Hi, can you provide below information, you may send those over email if needed wangxiao@microsoft.com
- Screen recording of the reproduce procedure, timestamps
- MAM logs https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-ios-appendix#how-can-i-troubleshoot-my-app
- Info.plist file

**Comment by edgar-yang** [comment]
Hi, thank you for your response. The issue cannot be reproduced in our latest build. We will continue to monitor it and provide updates as needed.
