### ISSUE TITLE
Question regarding hard requirement for MSAL

### ISSUE THREAD

**Issue by andrejacobs-unily** [microsoftconnect/ms-intune-app-sdk-ios#512]
While reading the implementation documentation, I came across this section:
https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-ios-phase1

Should my application integrate the Microsoft Authentication Library (MSAL)?
Yes, you are required to integrate with MSAL before integrating the Intune SDK. Before integrating with MSAL, all apps are required to register with the Microsoft identity platform.

--

My questions are:
* Does this mean that we must have an Azure App registered (with the redirect URI etc.) for MSAL and the app must be configured to use this Azure App's Client ID, Tenant etc?
* What if you are only using AutoEnrollOnLaunch? Does MSAL now have to be baked into the Info.plist?
* What if we are not using MSAL directly for authentication? Imagine app is using MAM (app is being compiled with MSAL). App is not configured with any MSAL details (client id etc. in the info.plist) and we are using Google for authentication.
* If the app must be configured to use MSAL (as in the client Id is baked into the app). When will this become a hard requirement from Microsoft? At the moment we have about 30+ apps which is using MAM with AutoEnrollOnLaunch and don't have MSAL details baked in (MSAL SDK is compiled into the app) ... and it works just fine.

Thank you

**Comment by andrejacobs-unily** [comment]
I noticed the documentation for Android is different for time being:

https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-android-phase1#should-my-application-integrate-the-microsoft-authentication-library-msal

---

Should my application integrate the Microsoft Authentication Library (MSAL)?
Refer to Overview of the Microsoft Authentication Library (MSAL) to determine whether your application will need to integrate MSAL. Most applications must integrate MSAL before integrating the Intune SDK.

Your app can skip integrating MSAL only if all of the following are true:

Your application doesn't have or need an interactive log-in and log-out end user experience.
Your application doesn't support multiple accounts logged in simultaneously.
Your application doesn't need to support non-Intune accounts.
Your application doesn't grant access to any resources protected by Conditional Access.
If your app satisfies all of the above conditions and doesn't integrate MSAL, it can still be protected by App Protection Policy, albeit with no option for unmanaged usage. See Default Enrollment for details.

---

So it seems to suggest that there are indeed certain conditions in which MSAL is not required, for Android at least.
We also know that it is not a hard requirement at the moment for iOS given we have 30+ working apps out there.

We are just worried that it could become a hard requirement in the future. Meaning one day we wake up to hundreds of support tickets and find out that the apps won't launch because they are only using the default MSAL details that MAM uses by default.

**Comment by wangxiaoms** [comment]
Hi, All apps integrating with the Intune SDK are required to register with the Microsoft identity platform. This is also true for auto enroll on launch option. 
- SDK: https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-ios-phase1#do-i-need-to-register-my-application-with-the-microsoft-identity-platform
- Wrapping tool: https://learn.microsoft.com/en-us/mem/intune/developer/app-wrapper-prepare-ios#register-your-app-with-microsoft-entra-id

Apps that don't sign in the user using MSAL can still receive app protection policy from the Intune MAM service by using the login and enroll option, or the auto enroll on launch option, app registration is still required.
https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-ios-phase3#apps-that-dont-use-adal-or-msal

Please migrate your apps to use your own app registration asap.
